### ISSUE TITLE
How to use the overlay as the basis for a development environment?

### ISSUE THREAD

**Issue by leungbk** [nix-community/emacs-overlay#101]
I'm not knowledgeable with the Nix language. I've seen other repos include a `flake.nix` enabling them to execute `nix develop` or similar to create a development environment for the corresponding repo. Is it currently possible to do something similar with the flake in this overlay to create an environment for compiling Emacs from a local repo?

**Comment by tadfisher** [comment]
> an environment for compiling Emacs from a local repo

You don't need this repo for that. In your flake, do something like

```nix
{
  description = "Emacs from local source";
  
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }: {
    package."x86_64-linux" = nixpkgs.legacyPacakges.emacs.overrideAttrs (attrs: {
      version = "unstable-2020-01-10";
      src = nixpkgs.lib.cleanSource ./.;
      srcRepo = true;
    });
  };
}
```

**Comment by leungbk** [comment]
Thanks!
