### ISSUE TITLE
works EXWM with native-comp or pgtk branch?

### ISSUE THREAD

**Issue by juaningan** [nix-community/emacs-overlay#102]
I'm trying to make it work but compilation crashes. I'm not sure if it is impossible to make it work or worth the time struggle with it.

**Comment by collares** [comment]
Please provide more information. How does it crash? Is it similar to https://github.com/nix-community/emacs-overlay/issues/74#issuecomment-758160258?

**Comment by juaningan** [comment]
Sorry, it a similar error.
