### ISSUE TITLE
No Melpa updates in six days

### ISSUE THREAD

**Issue by leungbk** [nix-community/emacs-overlay#107]
The Emacs and Elpa json files have been updating normally, but the Melpa json file hasn't updated in some time.

**Comment by talyz** [comment]
Thank you for reporting! Looking at the build logs, this seems to be the issue: https://github.com/NixOS/nixpkgs/pull/110626.

**Comment by terlar** [comment]
Now this has been merged and also a build after that has succeeded for nixpkgs unstable, however the pipeline still seems to fail. It says permission denied if I understand correctly. Not sure what's up...

https://hydra.nix-community.org/project/emacs-overlay
