### ISSUE TITLE
emacsWithPackagesFromUsePackage does not load (requires 'foo)

### ISSUE THREAD

**Issue by smsegal** [nix-community/emacs-overlay#109]
My Emacs configuration is split over a few files like so:

```lisp
;;;  relevant section of init.el
;; additional packages
(require '+evil)          ;; load evil configuration
(require '+ui)
(require '+project)
(require '+narrowing)     ;; incremental narrowing + utils (selectrum+consult+marginalia)
(require '+spellcheck)
(require '+modeline)
(require '+buffers)
```
where `use-package` is called inside each of those files to load the packages. Am I correct in assuming that the current implementation of `emacsWithPackagesFromUsePackage` can't handle this usecase?

Note: I'm fairly new to Nix, so I'm not currently capable of opening a PR for this. Hopefully one day soon!

**Comment by adisbladis** [comment]
> where use-package is called inside each of those files to load the packages. Am I correct in assuming that the current implementation of emacsWithPackagesFromUsePackage can't handle this usecase?

Indeed it cannot, and I don't think it's possible to implement it as a pure Nix function.

cc @talyz

**Comment by terlar** [comment]
One solution would be to just concat all contents of all el files recursively In a directory and run the use package logic on top of that (then it could still be done via nix). It feels like going down the route to handle requires will be quite sticky.

**Comment by talyz** [comment]
We'll probably never be able to read files by `require`s, since that would likely involve evaluating the code. What you could do, however, is listing all the files you want to read from like this:
```nix
builtins.concatStringsSep "\n" (map builtins.readFile ["/path/to/evil.el" "/path/to/ui.el"])
```
and feed that to the `config` parameter.

**Comment by smsegal** [comment]
I just gave that a try, it worked perfectly. Good stuff, thanks!

**Comment by adisbladis** [comment]
I'm going to close this for now as it looks like this is not realistic, and supporting `require` is out of scope.
