### ISSUE TITLE
emacs-git-commit fails to build on latest commit

### ISSUE THREAD

**Issue by arqv** [nix-community/emacs-overlay#110]
In the latest commit of this repository, the `emacs-git-commit` package (as a dependency of `magit`), fails to build under `emacsGcc`, (tested using the `home-manager` Emacs module). The package builds correctly under the `emacsGit` package (gets substituted from the Cachix binary cache).
To try to provide as much information as possible to help, I've done the following:
- I uninstalled Emacs (by removing the `enable` field in it's `home-manager` module), and ran `sudo nix-collect-garbage -d` to provide a clean environment to reproduce.
- I tested installing `emacsGcc` with `magit` outside the home-manager module:
  ```
  (pkgs.emacsPackagesGen pkgs.emacsGcc).emacsWithPackages (epkgs: with epkgs.melpaPackages; [
    magit 
  ])
  ```
  Which failed with the following log: https://pastebin.com/V5BbkphM
- After that, I ran `sudo nix-collect-garbage -d` again, just to be sure.
- Then, I installed the same package expression. replacing `emacsGcc` with `emacsGit`, which built successfully with the following log: https://pastebin.com/yJL0a7AM
- Just to be 100% sure, I tried again with both `emacsGcc` and `emacsGit` using `epkgs.melpaStablePackages` instead, obtaining the same results.

This is all using the latest `emacs-overlay` commit, and all the rebuild commands were run with the flags `-v -L --builders ''`.
The last commit that worked for me was `c052c8b1a02d2645abc1bad78ea391a9a2d1a43d`

**Comment by collares** [comment]
This was discussed in https://github.com/nix-community/emacs-overlay/issues/74#issuecomment-758160258. The TL;DR is that https://github.com/NixOS/nixpkgs/pull/109370 fixes it. Thanks for opening a separate issue, and sorry for wasting your time by not opening a separate issue myself.

**Comment by collares** [comment]
An alternate solution to this problem landed (see above) in nixpkgs, so this should be fixed once the channels update.
