### ISSUE TITLE
EmacsGcc cant find execvp

### ISSUE THREAD

**Issue by Redcroft** [nix-community/emacs-overlay#112]
Hi, installed emacsgcc using this guide 
https://gist.github.com/mjlbach/179cf58e1b6f5afcb9a99d4aaf54f549

fresh nixos 20.09 install, with home-manager 20.09 and cachix.

Then i get 'fatal error: cannot execute `as`: execvp: no such file or directory'

I can see old issue's for this which appears to be fixed

Thanks

**Comment by adisbladis** [comment]
Using `native-comp` is completely unsupported on 20.09.
