### ISSUE TITLE
help adding emacs-ng

### ISSUE THREAD

**Issue by kidd** [nix-community/emacs-overlay#114]
I've tried to add support for emacs-ng but I'm failing to get it working: 
My draft PR is in https://github.com/kidd/emacs-overlay/pull/1 (relevant commit here: https://github.com/kidd/emacs-overlay/pull/1/commits/88e0cdb1bd0757535b8d06eb53ccdbfe0a229b2a).

After some initial issues, it's now at a stage where it fails when trying to build the rust part.
The build process complains it needs internet access to get all cargo stuff, but nix doesn't allow it.  Tried `carnix` but I can't get it working. 

If anyone with more rust packaging experience could chime in, it'd be awesome to have emacsNg building in this emacs-overlay.

**Comment by Atemu** [comment]
Have a look into building the rust stuff using Nixpkgs' rust infra: https://nixos.org/manual/nixpkgs/stable/#rust

**Comment by adisbladis** [comment]
`emacs-ng` upstream has added Nix support.
