### ISSUE TITLE
csv-mode removed from elpa packages

### ISSUE THREAD

**Issue by svend** [nix-community/emacs-overlay#115]
This automated commit removed the `csv-mode` package from the `elpa` package set:

https://github.com/nix-community/emacs-overlay/commit/3e45bcf3aeefd64de4db88141046fe73fb630318#diff-9cebc0cb8dee22a08b42345e70eaca296357aaf6bef7b08cf65283545c0ff040L620-L634

`csv-mode` still shows up on ELPA here: https://elpa.gnu.org/packages/csv-mode.html

The package seems to be added and removed in previous commits too:

```
$ git log -S 'csv-mode =' -p -- repos/elpa/elpa-generated.nix | grep -E '^(commit|Date)|csv-mode ='
commit 3e45bcf3aeefd64de4db88141046fe73fb630318
Date:   Tue Feb 16 16:06:23 2021 +0000
-    csv-mode = callPackage ({ cl-lib ? null, elpaBuild, emacs, fetchurl, lib }:
commit d056d8ed762680f4795fe557afea3a1144eb48db
Date:   Thu Jan 14 04:08:43 2021 +0000
+    csv-mode = callPackage ({ cl-lib ? null, elpaBuild, emacs, fetchurl, lib }:
commit bf34f07cd91c3256fd7ee1a3e60dd0009d81a7fa
Date:   Thu Jan 14 00:05:59 2021 +0000
-    csv-mode = callPackage ({ cl-lib ? null, elpaBuild, emacs, fetchurl, lib }:
commit c26c5a387b05596864f205a92a7fb7a44f4f52f9
Date:   Tue Jan 12 08:09:08 2021 +0000
+    csv-mode = callPackage ({ cl-lib ? null, elpaBuild, emacs, fetchurl, lib }:
commit 95c580acaec8515d64f5c0bc05750b216176ef37
Date:   Mon Jan 11 16:05:54 2021 +0000
-    csv-mode = callPackage ({ cl-lib ? null, elpaBuild, emacs, fetchurl, lib }:
commit 5b9f3a8258c4b42c9c3dfcb77bde5d2e3abbc6eb
Date:   Sun Aug 18 12:38:20 2019 +0100
+    csv-mode = callPackage ({ elpaBuild, fetchurl, lib }:
```

**Comment by talyz** [comment]
This sounds like an issue in https://github.com/ttuegel/emacs2nix or with elpa reliability. It would likely be alleviated by fixing https://github.com/ttuegel/emacs2nix/issues/54; currently we have to remove the `elpa-generated.nix` file and generate it from scratch to avoid duplicates, but it would normally fall back to using the definitions in the file if the elpa query somehow fails.

**Comment by adisbladis** [comment]
Seems to have been alleviated since the issue was reported.
