### ISSUE TITLE
config file parser fails at prefix-less floats

### ISSUE THREAD

**Issue by antifuchs** [nix-community/emacs-overlay#116]
I had a `.7` in my config file, which the configuration file parser couldn't stomach: 

```
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '.'
```

that is a really unfortunate error, but what's more, I think it might need a special case for tokens that start with `.`.

**Comment by antifuchs** [comment]
(The work-around, of course, is to use `0.7` in the config file instead) (:

**Comment by adisbladis** [comment]
cc @talyz

**Comment by talyz** [comment]
Sorry, I completely missed this. I'll look into it.
