### ISSUE TITLE
alwaysEnsure notice can't be turned off?

### ISSUE THREAD

**Issue by antifuchs** [nix-community/emacs-overlay#117]
I've started using `emacsWithPackagesFromUsePackage` in my config, and started with `alwaysEnsure = false;` in my config. That results in emacs-overlay printing the following error whenever I rebuild:

```
trace: Emacs-overlay API breakage notice:

Previously emacsWithPackagesFromUsePackage always added every use-package definition to the closure.
Now we will only add packages with `:ensure`, `:ensure t` or `:ensure <package name>`.

You can get back the old behaviour by passing `alwaysEnsure = true`.
For a more in-depth usage example see https://github.com/nix-community/emacs-overlay#extra-library-functionality
``` 

I think it should only do this if you don't pass alwaysEnsure explicitly. I can make a PR to do that.

**Comment by adisbladis** [comment]
> I can make a PR to do that.

Please do! :)
