### ISSUE TITLE
emacsGcc uses "as" from PATH, doesn't work with LLVM as

### ISSUE THREAD

**Issue by langston-barrett** [nix-community/emacs-overlay#131]
When I tried out `emacsGcc` from this overlay, I got an error message about `as` not supporting the `--64` flag. The version of `as` on my `PATH` is:
```
$ as -version
LLVM (http://llvm.org/):
  LLVM version 7.1.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver1
```
When I restarted Emacs like so:
```
$ nix-shell -p coreutils --run "emacs -nw"
```
It worked fine. And here's the version of `as` in that environment:
```
$ nix-shell -p coreutils --run "as --version"
GNU assembler (GNU Binutils) 2.31.1
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-unknown-linux-gnu'.
```
EDIT: I spoke too soon, the following isn't true. Looks like GNU `as` needs to stick around.
~~Interestingly, once I had started Emacs in the environment with `as` from `coreutils`, I could start it in the other environment with no issues. So it appears that GNU `as` is a one-time setup dependency for `emacsGcc`.~~

**Comment by adisbladis** [comment]
This problem should really be fixed in nixpkgs. Could you report an issue there and reference this one?

**Comment by hmenke** [comment]
`as` is in `binutils`, not in `coreutils`. I also want to report the same problem, because I just don't have any `as` in my `$PATH`.

**Comment by adisbladis** [comment]
As previously stated this is not an overlay issue.
If the issue still persists it should be solved in nixpkgs.
