### ISSUE TITLE
[Error] Wrong type argument: number-or-marker-p, nil

### ISSUE THREAD

**Issue by Rizary** [nix-community/emacs-overlay#14]
After updating emacs-overlay to current master (less than 12 hours ago), I got the `Wrong type argument: number-or-marker-p, nil` for some of my packages (evil-org, evil-magit, etc) which is fine prior the update.

The following image is part of the error (which all other package error is similar)

![image](https://user-images.githubusercontent.com/7221768/72146105-5cb70800-33ce-11ea-8375-745bae5c03df.png)

**Comment by adisbladis** [comment]
Are you using the `emacsGit` package by any chance?

Either way, it's very likely that this issue has little to do with the overlay and has to do with upstream breakage.

I was seeing issues like this fairly frequently while using `emacsGit`, I have since reverted to using Emacs 26.

**Comment by Rizary** [comment]
@adisbladis yes I'm using `emacsGit`. I have listed my package in `package.nix`. Do you have any other way to handle all the packages using this overlay?

**Comment by adisbladis** [comment]
We can't reasonably guarantee stability with `emacsGit` since it's a rapid moving target, if you're using `emacsGit` you'll pretty much be on your own to fix your issues.

**Comment by adisbladis** [comment]
I've added a warning about stability to the readme, I think that's all we can do.

**Comment by Rizary** [comment]
@adisbladis I try to revert back to emacs 26 and using `emacsWithPackagesFromUsePackage` and the result didn't change.
List packages that failed to buid:
- evil-magit
- evil-collection
- evil-org
- evil-smaprtparens
- powerine-evil.

**Comment by etu** [comment]
@Rizary I'd say that this may be an issue that may have been introduced in any of the packages recently as well. We bump all the packages regularly regardless if they build/work or not since we don't test the packages in the update process.

**Comment by adisbladis** [comment]
To add to this: We ensure that the nix side of things is OK by evaluating all packages but we do not build them.

**Comment by Rizary** [comment]
@etu and @adisbladis thank you for the explanation.
