### ISSUE TITLE
 auctex needs to be updated

### ISSUE THREAD

**Issue by endgame** [nix-community/emacs-overlay#142]
auctex-13.0.10.tar is no longer available.

Previously: #140 #124 

A mirror, or a discussion with upstream, might be in order.

**Comment by kennyballou** [comment]
It's not really that it needs to be updated, but that there needs to be a stable URL for retrieving the package.  See https://github.com/nix-community/emacs-overlay/issues/125.

**Comment by endgame** [comment]
Seems to be fine again. For now.
