### ISSUE TITLE
Blank frame after virtual desktop switching on xmonad

### ISSUE THREAD

**Issue by psanford** [nix-community/emacs-overlay#146]
On xmonad, switching away from the virtual desktop emacs is on and then back, emacs shows a blank frame and does not redraw. The keyboard is still active (e.g. I can C-x C-c to exit emacs). 

This is with nix on Ubuntu 20.04. I also have emacs-27 installed from nix on this system which does not have this issue.

**Comment by talyz** [comment]
Which package from the overlay are you using? It's quite likely an upstream bug, especially if it's one of those built from master.

**Comment by psanford** [comment]
It was for `emacsGcc`

**Comment by collares** [comment]
I see a related bug: when `exwm` starts up, the screen is blank. It is not an `emacsGcc` bug, and reverting https://github.com/emacs-mirror/emacs/commit/483c5e953c12a95382bef4a3b6769a680c32fe86 fixes it. I will file a bug upstream.

**Comment by psanford** [comment]
Switching to an earlier version fixed this for me. :bow:

**Comment by collares** [comment]
Update: I just tried emacs master and exwm is working fine for me there (I tried with `emacsGcc` but that should be independent of native compilation). So the revert won't be needed as soon as #150 is fixed.
