### ISSUE TITLE
Emacs repo update is failing

### ISSUE THREAD

**Issue by mcwitt** [nix-community/emacs-overlay#152]
The automatic update of the emacs repo seems to be broken. The last commit with the description `Updated repos/emacs` was 69f6248df3ecb527fabbdf9bdb5264fb0ef47049, committed 8 days ago.

Not very confident in this, but it seems like the following error might be related (as far as I can tell started showing up in the action logs on [run #100](https://github.com/nix-community/emacs-overlay/runs/2547589117?check_suite_focus=true)):
```
builder for '/nix/store/w8p5hgqqlzl0sjdd27v8jvc0hisy50rf-emacs-pgtkgcc-20210510.0.drv' failed with exit code 255
cannot build derivation '/nix/store/32gaiiq8ig9a5vqmj0v4bkp084aadmkb-emacs-pgtkgcc-with-packages-20210510.0.drv': 1 dependencies couldn't be built
```

**Comment by bnjmnt4n** [comment]
See https://github.com/nix-community/emacs-overlay/issues/150#issuecomment-841059716.

**Comment by mcwitt** [comment]
Thanks! Since #150 is closed and this seems still an issue, I'll leave this open for now.

**Comment by talyz** [comment]
I've reopened #150.
