### ISSUE TITLE
seq.el.gz:397:16: Warning: ‘seq-contains’ is an obsolete generic function (as of 27.1); use ‘seq-contains-p’ instead. aarch64-unknown-linux-gnu-gcc-9.3.0: fatal error: cannot execute ‘as’: execvp: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by zeta-00** [nix-community/emacs-overlay#157]
Hello there,
Just wondering if this issue has been fixed?
I tried the fixes from this issue: https://github.com/nix-community/emacs-overlay/issues/33 ,
but the error still persists on my end.
If you could let me know if there's a fix thanks.
Note: I tried upgrading home-manager to unstable but got that: `anything not found  in home-manager/nixos/default.nix` error?
Also, I'm not sure if I'm supposed to use nixos-unstable channel as well to fix this emacsGcc issue.

Here's the instructions that I'm following: https://gist.github.com/mjlbach/179cf58e1b6f5afcb9a99d4aaf54f549 ,

emacsGcc built without any errors which is great, but whenever I open emacs, this error is thrown?
Also, I'm using nixos on a raspberry pi 4, regular emacs works fine, but emacsGcc is throwing this error?
I tried upgrading to the 21.05 stable channel, for nixpkgs and home-manager, but it's still broken, so I don't know if those channels have fixes either for this issue?

Thanks in advance for the help.

**Comment by adisbladis** [comment]
This is very out of date and probably is not an issue any more.
