### ISSUE TITLE
config file parser fails to recognize octals (#o prefix)

### ISSUE THREAD

**Issue by antifuchs** [nix-community/emacs-overlay#164]
I have had to chmod a custom server directory, using the following: `(set-file-modes server-socket-dir #o700)`; unfortunately, that causes the config file parser to be unhappy: `error: Unrecognized token on line 4694: #o700))`.

I worked around by using read-from-string, but it would be nice to have these supported natively. Here's the work-around: `(set-file-modes server-socket-dir (car (read-from-string "#o700")))`

I imagine it's similar to issue #116, I hope I'm not getting a reputation for finding the worst-possible ways to write numbers in emacs config files (-;

**Comment by adisbladis** [comment]
This should be reported upstream to https://github.com/talyz/fromElisp.
