### ISSUE TITLE
Can't figure how to get emacs 28

### ISSUE THREAD

**Issue by nazzacode** [nix-community/emacs-overlay#166]
Nix beginner here; I've been following the instructions on the README trying to get emacs28 up and running but I only ever seem to have emacs27.

Currently in my `configuration.nix`:
```nix
{ config, pkgs, callPackage, ... }:
{

  # ...

  environment.systemPackages = with pkgs; [ 
    emacsUnstable 
    # emacs
  ] 

  services.emacs.package = pkgs.emacsUnstable;

  nixpkgs.overlays = [
    (import (builtins.fetchTarball {
      url = https://github.com/nix-community/emacs-overlay/archive/master.tar.gz;
    }))
  ];

  # Enable daemon/server mode
  services.emacs.enable = true;

  # ...
}
```

What can I do to  make this work?

**Comment by leungbk** [comment]
Basically, just change `pkgs.emacsUnstable` to either `pkgs.emacsGit` or `pkgs.emacsGcc`.

`emacsUnstable` corresponds to the most up-to-date revision of the currently-stable version of Emacs (which is 27), whereas the other two correspond to the latest unreleased major version (28 at present).

Btw if you use `services.emacs`, you don't need to separately add Emacs to your `environment.systemPackages`.

**Comment by nazzacode** [comment]
Perfect, Thank you. Might it be possible to update the the README for those of us who don't have the background knowledge? Something like, 

```nix
{config, pkgs, callPackage, ... }:
{
# ...

  services.emacs.package = pkgs.emacsUnstable;  # emacs 27.2
  # services.emacs.package = pkgs.emacsGcc;       # emacs 28

  nixpkgs.overlays = [
    (import (builtins.fetchTarball {
      url = https://github.com/nix-community/emacs-overlay/archive/master.tar.gz;
    }))
  ];

# ...
}
```

**Comment by adisbladis** [comment]
@nazzacode Since your issue seems to be sorted I'm going to close this issue.

You'd be most welcome to submit a PR changing the README to be more clear :)
