### ISSUE TITLE
Ensure packages from MELPA are installed when using `emacsWithPackagesFromUsePackage`

### ISSUE THREAD

**Issue by cmacrae** [nix-community/emacs-overlay#169]
👋 

I've been using `emacsWithPackagesFromUsePackage` for quite some time and its always worked perfectly.  
However, I recently tried adding [orderless](https://github.com/oantolin/orderless) to my configuration, which breaks it.  
[orderless](https://github.com/oantolin/orderless/issues/57) isn't in GNU ELPA at the moment.  

I'd like to know how I can set up the overlay when using `emacsWithPackagesFromUsePackage` to install packages from MELPA?

**Comment by adisbladis** [comment]
They are already installed from MELPA (selected according to the merge logic in https://github.com/NixOS/nixpkgs/blob/dc79d3b0da29cd63e4e8498feaec23db0bcb6f84/pkgs/top-level/emacs-packages.nix#L72-L77).

**Comment by cmacrae** [comment]
@adisbladis Ah okay. Any ideas the following behaviour would be occurring?

**init.el**
``` elisp
(setq emacs-dir (file-name-directory (or (buffer-file-name) load-file-name)))

;; load up Org-mode and Org-babel
(require 'org-install)
(require 'ob-tangle)

;; load up all literate org-mode files in this directory
(mapc #'org-babel-load-file (directory-files emacs-dir t "\\.org$"))
```

**Relevant part of emacs.org**
```elisp
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless)
  (completion-category-defaults nil)
  (completion-category-overrides '((file (styles partial-completion))))
```

**Behaviour in \*Messages\***
Seems like rather than using the Nix package, it decides to try and install using the packaging functionality
```
Loading /nix/store/6b4i0lzyh4av0xkavprvyls4qs6nmnrh-emacs-with-packages-28/share/emacs/site-lisp/site-start.el (source)...done
Loading /Users/cmacrae/.emacs.d/emacs.el (source)...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443 [2 times]
Contacting host: elpa.nongnu.org:443 [2 times]
Package refresh done
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Package refresh done
...
```

**Behaviour in \*Warnings\***
For some reason, other packages I use are logged here, but only when using the above `orderless` config
```
Error (use-package): Failed to install org-superstar: Package ‘org-superstar-’ is unavailable Disable showing Disable logging
Error (use-package): Failed to install org-appear: Package ‘org-appear-’ is unavailable Disable showing Disable logging
```
