### ISSUE TITLE
More examples please (xwidgets)

### ISSUE THREAD

**Issue by 11111000000** [nix-community/emacs-overlay#17]
I'm new to overlays, can anybody explain how to add xwidgets  support etc?

**Comment by terlar** [comment]
You can specify a custom emacs package to use, and that is what you need to do in this case. Either on the fly or as a package in an overlay.

You can see how the package is defined here:
https://github.com/NixOS/nixpkgs/blob/release-20.03/pkgs/applications/editors/emacs/default.nix
And used by this overlay here:
https://github.com/nix-community/emacs-overlay/blob/master/default.nix#L24

You can see that you need to pass `withXwidgets = true` in the underlying package from nixpkgs. To do this via this overlay, you can see a hint from the emacsGit-nox derivation:
https://github.com/nix-community/emacs-overlay/blob/master/default.nix#L42-L48

To do it as an end user you would do:
```nix
{
  environment.systemPackages = [
    (emacsWithPackagesFromUsePackage {
      # Package is optional, defaults to pkgs.emacs
      package = (pkgs.emacsGit.override {
        withXwidgets = true;
      });
    })
  ];
}
```

Or perhaps the preferred way creating another overlay and defining the package there:
```nix
self: super:
{
  emacsGit-xwidgets = ((emacsGit.override {
    withXwidgets = true;
  }).overrideAttrs(oa: {
    name = "${oa.name}-xwidgets";
  }));
}
```
and then use this as your package.

**Comment by 11111000000** [comment]
Thank's you @terlar !
