### ISSUE TITLE
Whither org-mode?

### ISSUE THREAD

**Issue by jhenahan** [nix-community/emacs-overlay#174]
As of [9.5](https://orgmode.org/Changes.html), Org releases are through ELPA. I'd like to be able to use it, but it seems that the latest `orgPackages` version ends up in my load-path ahead of 9.5. I've tried to muck around with overrides to either null out `orgPackages` entirely or to explicitly override `org = epkgs.elpaPackages.org`, but in both cases I still end up with `org-20210920` from https://orgmode.org/elpa/ in my load-path. The only thing that "works" so far is to use a fork of the overlay with `org-generated.nix` emptied out. That feels like a big hammer, so I'm happy to do whatever work in the overlay to give some way of preferring the newer Org releases over the old ones, I just need a pointer to where that work needs to be done.

**Comment by matthuszagh** [comment]
I'm experiencing the same issue. It would be nice for all third party packages to not be added to the build share directory unless explicitly added (e.g., with `emacsWithPackages`). Happy to post my configuration, etc. if that's helpful.

**Comment by matthuszagh** [comment]
In case it's helpful to someone else who experiences this, I'm currently using the following to remove the nix store org from the load path. It's a hack, and it relies on the fact that org resides in its own subdirectory (and therefore may not work for another third party package that shouldn't be loaded), but it does the trick here:

```elisp
(require 'dash)
(setq load-path
      (-remove (lambda (path)
                 (string-equal (substring path -3 nil) "org"))
               load-path))
```
