### ISSUE TITLE
Add version pulled from emacs-28 branch

### ISSUE THREAD

**Issue by catern** [nix-community/emacs-overlay#176]
The emacs-28 branch, which will become Emacs 28.1, has been cut.  Ideally, it's more stable than master, and anyone who wants to contribute to testing Emacs should run emacs-28 and report bugs.

Should emacsUnstable be updated to pull from emacs-28? Or should there be another attribute added - emacsRc, maybe?

**Comment by rrix** [comment]
I mentioned this in Matrix the other day, but I think that emacsGcc should be switched to the emacs-28 branch as well.

**Comment by adisbladis** [comment]
I don't think we should be adding derivations for 28 specifically, but instead rely on `emacsUnstable`.

**Comment by catern** [comment]
For anyone finding this issue later, emacsUnstable now points to a 28 release, as of https://github.com/nix-community/emacs-overlay/commit/5e7af7d4bda485bb65a353d16a1ca38d9b73b178 so you can just use emacsUnstable.

In the future, it would really be nice to have a way to track the release branch (e.g. the 29 branch) with emacs-overlay.
