### ISSUE TITLE
merlin from melpa has broken version info

### ISSUE THREAD

**Issue by sheijk** [nix-community/emacs-overlay#178]
In [the melpa archive](repos/melpa/recipes-archive-melpa.json) the merlin package's stable info has invalid version info. It should be 4.3.1 but is 4.3.1.-4.412. In the [matching commit](https://github.com/ocaml/merlin/commit/ba8ec63cf40b8999238c4639d111ca3bdb1e34cf) of Merlin the version string changed from 4.3 to 4.3.1. This release was also tagged as `v4.3.1-412`, probably marking this for OCaml 4.12 (vs the `v4.3.1-411` tag for OCaml 4.11)

Trying to use it results in the following output:
```
these derivations will be built:
  /nix/store/29dkqj6bajngr81lgsfsnnfa1grwq52c-emacs-merlin-4.3.1.-4.412.drv
  /nix/store/csq1kcvm5czbpmsa6133r4ypqy343k1m-emacs-packages-deps.drv
  /nix/store/rmc2fc8sd5bni33qk3dcx2x7znvfi9sx-emacs-with-packages-27.2.drv
building '/nix/store/29dkqj6bajngr81lgsfsnnfa1grwq52c-emacs-merlin-4.3.1.-4.412.drv'...
unpacking sources
unpacking source archive /nix/store/byjvky0i7mricbp1q84mi3fib7jrj99j-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
Copying files (->) and directories (=>)
  from /build/working/merlin/
  to /build/merlinY8Ndag/merlin-4.3.1.-4.412
  ! emacs/merlin-cap.el -> merlin-cap.el
  ! emacs/merlin-imenu.el -> merlin-imenu.el
  ! emacs/merlin-xref.el -> merlin-xref.el
  ! emacs/merlin.el -> merlin.el
Invalid version syntax: `4.3.1.-4.412'
builder for '/nix/store/29dkqj6bajngr81lgsfsnnfa1grwq52c-emacs-merlin-4.3.1.-4.412.drv' failed with exit code 255
cannot build derivation '/nix/store/rmc2fc8sd5bni33qk3dcx2x7znvfi9sx-emacs-with-packages-27.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/rmc2fc8sd5bni33qk3dcx2x7znvfi9sx-emacs-with-packages-27.2.drv' failed
```

The dune package has a similar issue, showing a version number of  3.0.-3, it looks like it picked up some tag like `3.0-alpha` from [here](https://github.com/ocaml/dune/tags)

**Comment by adisbladis** [comment]
Could you report this issue to Melpa instead, since they are the ones generating broken version info in their json output.
We are merely consumers of it.
You can see that even the melpa webpage is reporting incorrect versions: https://stable.melpa.org/#/?q=merlin.

I've tapered over the issue in https://github.com/NixOS/nixpkgs/pull/154066 but ideally we'd not be required to do anything like that.

**Comment by sheijk** [comment]
Sorry for the delay. Finally reported the bug to both Melpa and merlin (links above)

**Comment by sheijk** [comment]
Merlin's maintainers decided to leave this as is (as far as I understand because they consider the generated version number valid even though it can be surprising). See ocaml/merlin#1442. 

They also pointed out that the occurrence of negative numbers in Melpa versions is to be expected and documented. See https://github.com/ocaml/merlin/issues/1442#issuecomment-1083581831 and https://github.com/melpa/melpa/issues/7946#issuecomment-1073300161. So either NixOS/nixpkgs#154066 needs to be permanent or possibly changed to not remove negative values.

**Comment by sheijk** [comment]
@adisbladis I can't reopen this. Could you do that?
