### ISSUE TITLE
`lsp-install-server` and this overlay

### ISSUE THREAD

**Issue by dhess** [nix-community/emacs-overlay#183]
Thanks very much for this overlay. It's made configuring and maintaining Emacs much, much easier than it used to be.

The only things I'm still dissatisfied with in my own setup are LSP and its language servers. Emacs constantly prompts me to install a language server when I visit a file that LSP supports, and when I relent, it downloads the server and installs it somewhere in my `~/.emacs.d` directory.

Obviously I'd like to do this declaratively, via this overlay, but it's not clear to me how to do that. Is there a way to pre-install language servers in one's overlay, rather than allowing Emacs to do it imperatively, or running `lsp-install-server` by hand?

**Comment by terlar** [comment]
I am not using `lsp-mode`, but I have solved similar issues for other packages. You can build the packages and replace the paths to the binaries to the ones in the nix store.

For example for theme magic, I do (where the patch replaces all occurrences with `@var@` with the actual path in store:
```
  theme-magic = epkgs.melpaPackages.theme-magic.overrideAttrs (attrs: {
    patches = [
      (substituteAll {
        src = ./patches/theme-magic.patch;
        python = "${python3}/bin/python";
        wal = "${pywal}/bin/wal";
      })
    ];
  });
```

However looking at the documentation, seems there is a way to configure this:
https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L7298-L7314

So all you have to do is to generate a file that will be included in your config that sets all the paths to the language servers you use:
```
            extraEmacsPackages = epkgs: [
              (epkgs.trivialBuild {
                pname = "lsp-install-servers";
                version = "1.0";
                src = pkgs.writeText "lsp-install-servers.el" ''
                  (eval-after-load 'lsp-mode
                     '(progn
                        (require 'lsp-javascript)
                        (lsp-dependency 'typescript-language-server `(:system "${pkgs.nodePackages.typescript-language-server}/bin/typescript-language-server"))
                        (lsp-dependency 'typescript `(:system "${pkgs.nodePackages.typescript}/bin/tsserver"))))
                '';
                packageRequires = with epkgs; [ lsp-mode ];
              })
            ];
```

**Comment by dhess** [comment]
Thanks for the help! I'll try this out and report back.

**Comment by peterstuart** [comment]
Alternatively, if you use [lorri](https://github.com/nix-community/lorri) to set up project-local environments which include the language server, along with the [direnv](https://github.com/wbolster/emacs-direnv) mode, `lsp-mode` mode will find the language server local to that project. (This works for me with the TypeScript and Rust language servers—I haven't tried any others.)

**Comment by dhess** [comment]
@peterstuart Thanks. We do use `direnv` via `nix-direnv`, rather than `lorri`, but to the same effect; and we do install `typescript-language-server` and other language server Node packages in our Nix shell. But in certain cases, Emacs either doesn't find, or doesn't recognize, the required binaries. (All other non-`emacs-lsp` modes work fine with `direnv`.) This only seems to affect some `lsp-mode` servers. For example, `eslint` works great, but `ts-ls` doesn't.

**Comment by talyz** [comment]
I use a very simple wrapper to make language servers available to emacs: https://github.com/talyz/nixos-config/blob/master/modules/emacs.nix#L39-L51.

**Comment by adisbladis** [comment]
Ideally these would be overridden in https://github.com/adisbladis/nixpkgs/tree/master/pkgs/applications/editors/emacs/elisp-packages for each individual package.

Of course that is a lot of work, so something like the wrapper proposed by @talyz might be more pragmatical.

Another option would be to make the Emacs wrapper add inputs to `$PATH` (on the fence whether it's a good idea or not).

A third option is to override the package and add inputs to `propagatedUserEnvPkgs` which might be the better solution.
A huge plus is that it's trivial and quite pragmatical.

Personally I think I'd just "yolo" it and install whatever language servers in my user profile.

In any case this isn't an issue with the overlay as such, so I'm closing this.
Whatever we decide to do these fixes belong in nixpkgs.
