### ISSUE TITLE
Separate branches for major emacs releases

### ISSUE THREAD

**Issue by pgronkievitz** [nix-community/emacs-overlay#185]
Actually emacs 29 can cause some breakage - (eg. hlissner/doom-emacs#5785). It might be a good idea to maintain separate branch for every major release - eg. `emacs-28` for 28, `emacs-27` for 27 and `master` for "currently in development". For now it's quite difficult to find the latest version for 28 between all of the commits - this may make it a little bit easier

**Comment by etu** [comment]
I for one thinks it's a terrible idea to have separate branches of this overlay, both that it would duplicate some of the updater work to commit the same changes (for melpa, etc) to several places, but also it would break everyones usecase that follows the `master` branch that would have to change whichever branch they are tracking.

If we should decide to change anything it would be to *add new* attribute names and let the existing ones be, say, `emacs28` and `emacs29` as new attribute names. Then the `emacsGit` and `emacsUnstable` and whatever they are called can point at one of these. That way we don't directly break peoples configuration but at the same time we enable some more fine control and make it easier to know what you're getting.

**Comment by pgronkievitz** [comment]
Yeah, that's for sure better solution - branch separation was the first thing I could think of as I'm kinda fresh in Nix
