### ISSUE TITLE
emacsGcc build failure with the latest develop

### ISSUE THREAD

**Issue by vmandela** [nix-community/emacs-overlay#189]
I am seeing a compiler error when trying to build emacsGcc from the latest develop (cb52bccea4e9). Does anyone see a similar issue ?

`In toplevel form:
/nix/store/yyjmd0svrpnzz80q964za89zwwb41wvr-emacs-gcc-20211123.0/share/emacs/site-lisp/site-start.el:54:17:
    Warning: reference to free variable `comp-eln-load-path'
/nix/store/yyjmd0svrpnzz80q964za89zwwb41wvr-emacs-gcc-20211123.0/share/emacs/site-lisp/site-start.el:54:17:
    Warning: assignment to free variable `comp-eln-load-path'
Generating native-compiled trampolines...
 Warning: `set-window-redisplay-end-trigger' is an obsolete function (as of
    23.1).
 Warning: `string-make-unibyte' is an obsolete function (as of 26.1); use
    `encode-coding-string'.
 Warning: `string-as-multibyte' is an obsolete function (as of 26.1); use
    `decode-coding-string'.
 Warning: `invocation-directory' is an obsolete function (as of 27.1); use the
    variable of the same name.
 Warning: `buffer-has-markers-at' is an obsolete function (as of 24.3).
 Warning: `string-as-unibyte' is an obsolete function (as of 26.1); use
    `encode-coding-string'.
 Warning: `string-make-multibyte' is an obsolete function (as of 26.1); use
    `decode-coding-string'.
 Warning: `run-window-configuration-change-hook' is an obsolete function (as
    of 27.1).
 Warning: `invocation-name' is an obsolete function (as of 27.1); use the
    variable of the same name.
 Warning: `window-redisplay-end-trigger' is an obsolete function (as of 23.1).
Debugger entered--Lisp error: (void-variable comp-eln-load-path)
  add-to-list(comp-eln-load-path "/nix/store/yyjmd0svrpnzz80q964za89zwwb41wvr-emacs-...")
  command-line-1(("--eval" "(add-to-list 'comp-eln-load-path \"/nix/store/yyjmd..." "-f" "batch-native-compile" "/nix/store/yyjmd0svrpnzz80q964za89zwwb41wvr-emacs-..."))
  command-line()
  normal-top-level()

builder for '/nix/store/zbhy9f6p1dx1iw9s1qx2mqj3iv2g2a16-emacs-gcc-20211123.0.drv' failed with exit code 255
error: build of '/nix/store/zbhy9f6p1dx1iw9s1qx2mqj3iv2g2a16-emacs-gcc-20211123.0.drv' failed
`

**Comment by collares** [comment]
Are you using an old version of Nixpkgs? NixOS/nixpkgs#121954 was supposed to fix this.

**Comment by adisbladis** [comment]
Hydra builds are still succeding, very likely the problem is an outdated nixpkgs.
