### ISSUE TITLE
emacs-phps-mode is stuck on hydra

### ISSUE THREAD

**Issue by vale981** [nix-community/emacs-overlay#195]
https://hydra.nix-community.org/build/10630963/nixlog/1/tail
expects manual input. 

Is this fixable?

**Comment by adisbladis** [comment]
This is fixed by https://github.com/NixOS/nixpkgs/pull/151334.

**Comment by collares** [comment]
OMG https://raw.githubusercontent.com/cjohansson/emacs-phps-mode/master/phps-mode-parser.el

**Comment by adisbladis** [comment]
@collares It's crazy but in a cool kind of way :laughing: 
If anything this is probably a prime example of something that is greatly benefited by native compilation.

**Comment by adisbladis** [comment]
And since this is now merged upstream (nixpkgs) and backported I'll close this issue.
