### ISSUE TITLE
Hydra evaluation failure

### ISSUE THREAD

**Issue by zeorin** [nix-community/emacs-overlay#204]
https://hydra.nix-community.org/jobset/emacs-overlay/unstable#tabs-errors:
```
error fetching latest change from git repo at `git://github.com/NixOS/nixpkgs.git':
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
This means that no builds are being done and no updates are being pushed to cachix.

The last successful evaluation was https://hydra.nix-community.org/eval/399080

**Comment by adisbladis** [comment]
Fixed in d223b464c6edffe88015c390cc137ee2eab64090 + 57378ea2f62e9f450f420dc9d01cc06e0d3dd15e (two separate commits because I'm an idiot who forgot to update both locations).
