### ISSUE TITLE
Cachix not being updated?

### ISSUE THREAD

**Issue by tadfisher** [nix-community/emacs-overlay#206]
I'm using the flake, and it seems I am not able to substitute `emacsPgtkGcc` from the nix-community cache. I haven't tried the other emacs derivations.

Looking at the GH actions runs, the cachix update is failing:

```
 Post job cleanup.
Cachix: push
  Pushing is disabled as signingKey nor authToken are set (or are emtpy?) in your YAML file.
```

**Comment by dschrempf** [comment]
`emacsUnstable` isn't in the cache either, so I think all packages are involved.

**Comment by adisbladis** [comment]
This has nothing to do with this repository as such, and should be addressed in https://github.com/nix-community/infra.

**Comment by adisbladis** [comment]
To clarify: This has to do with the Hydra setup and Nix/Hydra breaking what's allowed in restricted mode.

**Comment by adisbladis** [comment]
Builds are running on Hydra again.
Culprits: https://github.com/NixOS/nix/issues/5980 & https://github.com/NixOS/nix/issues/5998

**Comment by dschrempf** [comment]
Thank you very much!
