### ISSUE TITLE
emacs-master not being updated daily

### ISSUE THREAD

**Issue by ntharim** [nix-community/emacs-overlay#211]
It was last updated 11 days ago https://github.com/nix-community/emacs-overlay/commit/ccdabce3ab043dbe2f2a9967bb3ac292261ea1ce.

**Comment by bhankas** [comment]
Thanks for reporting. I've been building Emacs form master after forking this repo for past week and can confirm that everything works fine.

**Comment by barryfm** [comment]
@bhankas, What do you mean by your response, "everything works fine"?  It seems like you are saying that the lack of changes has to do with Emacs master being broken, not something on the Nix side.

**Comment by montchr** [comment]
Looks like unstable also needs an update, though it's possible it's only supposed to be updated manually (I'm not sure). 28.0.92 was tagged a couple days ago but `emacs-unstable.json` still points to 28.0.91. 

https://git.savannah.gnu.org/cgit/emacs.git/tag/?h=emacs-28.0.92

**Comment by bhankas** [comment]
Emacs repo was updated today. I think it is safe to close this one now as fixed under #73 .
