### ISSUE TITLE
Hydra jobset for `aarch64-linux`

### ISSUE THREAD

**Issue by aciceri** [nix-community/emacs-overlay#216]
Every time I update my ARM device I must rebuild the Emacs (`emacsPgtkGcc`) derivation since it isn't in the binary cache. Is there a particular reason for that?
I don't know if `nix-community`'s Hydra instance has a `aarch64-linux` machine but it should be possible to cross-compile.

I am quite ignorant about Hydra but I think this should be doable (and I could try on a local instance).

**Comment by aciceri** [comment]
@adisbladis maybe do you know why `aarch64_linux` isn't supported and if I can try to add support to it?

**Comment by adisbladis** [comment]
We don't have a builder for aach64 currently.
It's possible that we could potentially use https://github.com/nix-community/aarch64-build-box (but I'm reluctant given how many users are trusted on that machine) or binfmt-misc (qemu-user) emulation to add support.

I would probably be more inclined to go with the binfmt approach here given the trust issues and limit the builds to only include the emacs derivation itself but not it's packages.

**Comment by aciceri** [comment]
I didn't know about `aarch64-build-box` but I understand your concerns, cross-building only Emacs derivations using QEMU looks good to me.

However, I installed a local Hydra instance on my pc with
```nix
services.hydra = {
    enable = true;
    hydraURL = "http://localhost:3000";
    notificationSender = "hydra@localhost";
    buildMachinesFiles = [ ];
    useSubstitutes = true;
};
```
and then I created an user but when I try to execute the jobsets generated by `emacs-overlay` I get the following error:
```
command `nix-prefetch-git /var/lib/hydra/scm/git/6f4cdc603932b8be6d50758a9d11446c4141fdcff359ecd8ed5bca1b34c9c751 ce5ae7e90a5e1dcdabddada5ad0881c9e17c7abe' failed with exit status 256 (in an indeterminate location) at /nix/store/3r9j89l4cf32mhxd56zn963d3vj8r20g-hydra-2021-08-11/libexec/hydra/lib/Hydra/Helper/Nix.pm line 439.
```

This is the project configuration:
 
![image](https://user-images.githubusercontent.com/2318843/163377320-daa3eea1-e248-4faf-8e73-98698931b89c.png)

Am I missing something?

I tried other permutations for `input` like `ssh://git@github.com:nix-community/emacs-overlay.git` but it never worked. What is using the current `nix-community`'s Hydra instance?
