### ISSUE TITLE
Add a package output

### ISSUE THREAD

**Issue by NobbZ** [nix-community/emacs-overlay#221]
Currently there is only the overlay, which has its problems, though it has its benefits as well.

To mitigate the problems (especially cache misses), can we add additional `package` output for each build, that is only affected by the `nixpkgs` input and gets synced/updated daily?

This way it would be much easier to avoid cache misses and at the same time it would make it much easier to reason about them.

**Comment by drishal** [comment]
Would definitely love that!

**Comment by LogicalOverflow** [comment]
Another nice side-effect of that would be, that `nix search github:nix-community/emacs-overlay` would "just work" for searching the available packages.

**Comment by adisbladis** [comment]
This wouldn't really help with the current setup as we are not using flakes for managing channels, and I'm not interested in starting to do so.

**Comment by adisbladis** [comment]
I've added a `packages` output in e47ffb5d60d8e8271d412945c685dbeac2fca7a4, though we still don't have a `flake.lock` that provides anything useful to get better cache hits.

**Comment by ajgrf** [comment]
I just got this error when I tried updating this morning:

```
building the system configuration...
warning: Git tree '/home/alex/src/dotfiles' is dirty
error: attribute 'optionalAttrs' missing

       at /nix/store/c7m5qariaiqdimzvwmjg2jhasvpjspbw-source/default.nix:180:6:

          179|
          180| } // super.lib.optionalAttrs (super.config.allowAliases or true) {
             |      ^
          181|   emacsGcc = builtins.trace "emacsGcc has been renamed to emacsNativeComp, please update your expression." emacsNativeComp;(use '--show-trace' to show detailed location information)
```

If I remove those last few lines the error goes away, and nix doesn't complain about any of the other uses of `optionalAttrs` in the rest of the file.

**Comment by adisbladis** [comment]
> I just got this error when I tried updating this morning:
> 
> ```
> building the system configuration...
> warning: Git tree '/home/alex/src/dotfiles' is dirty
> error: attribute 'optionalAttrs' missing
> 
>        at /nix/store/c7m5qariaiqdimzvwmjg2jhasvpjspbw-source/default.nix:180:6:
> 
>           179|
>           180| } // super.lib.optionalAttrs (super.config.allowAliases or true) {
>              |      ^
>           181|   emacsGcc = builtins.trace "emacsGcc has been renamed to emacsNativeComp, please update your expression." emacsNativeComp;(use '--show-trace' to show detailed location information)
> ```
> 
> If I remove those last few lines the error goes away, and nix doesn't complain about any of the other uses of `optionalAttrs` in the rest of the file.

You're likely running in to https://github.com/divnix/digga/issues/464 which is incorrectly handling overlays.

**Comment by ajgrf** [comment]
Thanks, that was indeed the issue!

**Comment by NobbZ** [comment]
@spacekitteh `nixpkgs.overlays = [ emacs-overlay ];` and `programs.emacs.packages = pkgs.emacsGit;` (or whichever you want/need)

**Comment by adisbladis** [comment]
I'm going to close this issue since we now have package outputs in the flake.
If someone wants to add a hook to Hydra to pin the flake inputs and push the repo after the builds are done: patches welcome.
