### ISSUE TITLE
Add new attribute emacsGitNativeComp

### ISSUE THREAD

**Issue by benjaminor** [nix-community/emacs-overlay#222]
Hi, would it be possible to add a new attribute `emacsGitNativeComp`?
This attribute could look like this:

```nix
  emacsGitNativeComp = mkGitEmacs "emacs-git-native-comp" ./repos/emacs/emacs-master.json { nativeComp = true; withSQLite3 = true; };
```

This would enable an emacs build from master with native compilation enabled, but without the pure GTK addition, which some users might prefer, see for example https://lists.gnu.org/archive/html/emacs-devel/2022-04/msg00761.html.

Given that emacsNativeComp/emacsGcc now exists in nixpkgs, I think this attribute would be a valuable addition to this overlay.

**Comment by adisbladis** [comment]
I would welcome such a PR.
