### ISSUE TITLE
Support for tree-sitter

### ISSUE THREAD

**Issue by bhankas** [nix-community/emacs-overlay#226]
Upstream Emacs repo now has a tree-sitter branch available : https://git.savannah.gnu.org/cgit/emacs.git/log/?h=feature/tree-sitter

Although there is already pretty decent tree-sitter integration available in nixpkgs with external Elisp package, there are few benefits of using built-in support.

Separate derivation should also allow people to test out upstream changes as with pgtk and native-comp branches before.

**Comment by jian-lin** [comment]
FYI #254
