### ISSUE TITLE
Packages with non standard build process (e.g. transient & with-editor) fail when attempting to build

### ISSUE THREAD

**Issue by lyderichti59** [nix-community/emacs-overlay#229]
Hi,

I'd be happy to post a PR with the below solution if it suits you, but I'm not sure with the best approach so feel free to provide feedback please.

Today, when I tried to add the `transient` and `with-editor` epks to the list of  `extraPackages` my emacs package uses, I encountered strange issues (with both `transient`  and `with-editor`). Here's the issue for `transient`  :
```
Error: error ("No matching file(s) found in /build/working/transient/: (*.el *.el.in dir *.info *.texi *.texinfo doc/dir doc/*.info doc/*.texi doc/*.texinfo` (:exclude .dir-locals.el test.el tests.el *-test.el *-tests.el))")
```

After a bit of analysis, I spotted that these code repositories relied on code generation thanks to makefiles.
Consequently, I've added some overrides in my local config, in order to "prepare the build" by calling the right make commands before the code gets packaged.

Here's the fix that worked for me :

```nix
 {overrides = (self: super: {
        transient = super.transient.overrideAttrs (attrs : {
          buildInputs = (attrs.buildInputs or []) ++ (with pkgs; [gnumake texinfo texi2html texi2mdoc texlive.combined.scheme-medium]);
          preBuild = (attrs.preBuild or "") + ''
            make all
            mv lisp/* ./
          '';
        });
        with-editor = super.with-editor.overrideAttrs (attrs : {
          buildInputs = (attrs.buildInputs or []) ++ (with pkgs; [gnumake texinfo texi2html texi2mdoc texlive.combined.scheme-medium]);
          preBuild = (attrs.preBuild or "") + ''
            make all
            mv lisp/* ./
          '';
        });
      });}
```

What's the best way to include these overrides upstream in the `emacs-overlay` repo directly so that no one else encounters the issue ?

**Comment by adisbladis** [comment]
These should go in nixpkgs https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/elisp-packages/melpa-packages.nix.

**Comment by adisbladis** [comment]
These should go in nixpkgs https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/elisp-packages/melpa-packages.nix.

**Comment by adisbladis** [comment]
Closing this as the issue lies elsewhere.
