### ISSUE TITLE
`vterm` doesn't work

### ISSUE THREAD

**Issue by andrea96** [nix-community/emacs-overlay#23]
This overlay installs without errors the package `vterm`, but when I start Emacs I get the following error:

    Error (use-package): vterm/:catch: Loading file /nix/store/dpa9kscsc8yj8dzbnvdawi4ib4p0v3yk-emacs-vterm-20200407.1519/share/emacs/site-lisp/elpa/vterm-20200407.1519/vterm.elc failed to provide feature ‘vterm’

I get the same error both with `emacs` and `emacsUnstable`, this error apperead recently when I did a `nixos-rebuild switch`, I know that the error message is really poor but I don't know how to provide more information.

Maybe this isn't caused by the overlay (but I don't know how to determine it) since I touched many configuration files recently, of both NixOs and Emacs.

**Comment by vdemeester** [comment]
Upstream issue is there : https://github.com/akermu/emacs-libvterm/issues/291

**Comment by andrea96** [comment]
They solved the problem closing the issue that @vdemeester cites in the previous message, now everything works.
