### ISSUE TITLE
Updating the downstream project description in MELPA Wiki

### ISSUE THREAD

**Issue by akirak** [nix-community/emacs-overlay#238]
Hello,

MELPA is adding support for new host-specific fetchers which you can specify in recipes (https://github.com/melpa/melpa/issues/8043). Since this change can cause breakage in its downstream projects (e.g. package managers), they have created [Downstream Projects](https://github.com/melpa/melpa/wiki/Downstream-Projects) list.

I have added descriptions of nixpkgs and emacs-overlay to the page, but please feel free to edit it if you have an idea for improving it. I will close this ticket in time.

**Comment by adisbladis** [comment]
Thank you so much for this!

**Comment by akirak** [comment]
You're welcome. If you want to stay notified, please add your name to the bottom of the wiki page.
