### ISSUE TITLE
How to bulid emacs 28 pgtk

### ISSUE THREAD

**Issue by patrickaldis** [nix-community/emacs-overlay#239]
Hi, I was just wondering what the current method was for getting the overlay for emacs 28 pgtk - I've seen this pr https://github.com/nix-community/emacs-overlay/pull/188 and https://github.com/nix-community/emacs-overlay/pull/218, however can't find any tags mentioned in any commits?

**Comment by leungbk** [comment]
The PGTK stuff is not contained in Savannah's Emacs 28 branch afaik; you'd need to use Emacs 29.

**Comment by adisbladis** [comment]
Closing as Pgtk isn't on a release branch.
