### ISSUE TITLE
Latest update broke pgtk build

### ISSUE THREAD

**Issue by greydot** [nix-community/emacs-overlay#248]
Hello!

After this (https://github.com/nix-community/emacs-overlay/commit/6346fa5aa82fd663d340fe1e16e213128cad7542) commit, emacs built with pgtk is no longer able to render images and crashes with loaded with custom gtk modules.

I suppose, `withGTK3 = true` flag is still required even for PGTK build.

**Comment by lelit** [comment]
I'm experiencing the same: `report-emacs-bug` shows something like
```
Configured using:
  'configure ... --with-png=no --with-jpeg=no ...'
```

**Comment by leungbk** [comment]
Sorry, submitted a reversion PR just now.

> and crashes with loaded with custom gtk modules.

Could you explain how to reproduce this? Thanks.

**Comment by greydot** [comment]
> Could you explain how to reproduce this? I think I know how to fix the image-rendering, but I am not knowledgeable with GTK, and did only rudimentary testing with the PGTK build after my commit. Thanks, and I apologize again for the bug.

Launch emacs (or any other GTK program) with `GTK_MODULES` variable set to a list of modules you want loaded. This would require you to actually build some third-party modules to test, appmenu-gtk is a good candidate. It's not in NixOS though.
