### ISSUE TITLE
Make tree-sitter-based builds work on macOS

### ISSUE THREAD

**Issue by leungbk** [nix-community/emacs-overlay#258]
I tried simply changing `.so` to `.dylib` [here](https://github.com/nix-community/emacs-overlay/blob/dd6b9bbc728b9eb1c53738cf64d067384dfa269a/overlays/emacs.nix#L76) a few weeks ago but found that it wasn't enough to build successfully on aarch64-darwin. I am not a heavy macOS user, so it would be much appreciated if someone who is could submit a PR.

**Comment by jasonjckn** [comment]
The shared objects in https://github.com/emacs-tree-sitter/tree-sitter-langs purportedly are compatible with tree-sitter master, I still can't get it working though, maybe you'll have more luck.

**Comment by c4710n** [comment]
The dynamic link problem can be solved by replacing https://github.com/nix-community/emacs-overlay/blob/master/overlays/emacs.nix#L75-L77 with following code:

```
libName = drv: super.lib.removeSuffix "-grammar" drv.pname;
libSuffix = if super.stdenv.isDarwin then "dylib" else "so";
lib = drv: ''lib${libName drv}.${libSuffix}'';
linkCmd = drv:
  if super.stdenv.isDarwin then ''
    cp ${drv}/parser $out/lib/${lib drv}
    /usr/bin/install_name_tool -id $out/lib/${lib drv} $out/lib/${lib drv}
  '' else ''
    ln -s ${drv}/parser $out/lib/${lib drv}
  '';
```

But I still get the `codesign` problem when building it on a M1 machine:

```
cp -f temacs bootstrap-emacs
rm -f bootstrap-emacs.pdmp
./temacs --batch  -l loadup --temacs=pbootstrap
make[1]: *** [Makefile:835: bootstrap-emacs.pdmp] Killed: 9
```

> This issue should be solved by https://lists.gnu.org/archive/html/emacs-devel/2021-03/msg01338.html, but it occurs in my case.

;(

Maybe some Nix expert can solve this problem...

**Comment by jasonjckn** [comment]
@c4710n  that's very helpful thanks, 

I'm not getting codesign issues, I'm not sure what I did to fix it, you can try my build here if you want

https://github.com/jasonjckn/nix-emacs-flake

nonetheless, i'm stuck on the error
`
 ■  Warning (treesit): Cannot activate tree-sitter, because language definition for bash is unavailable (not-found): (libtree-sitter-bash.so libtree-sitter-bash.dylib) No such file or directory`

**Comment by jasonjckn** [comment]
Actually, nvm, I got it working, see my [build](https://github.com/jasonjckn/nix-emacs-flake). Other than what [c4710n](https://github.com/c4710n) said, i'm not sure what the key change was (if any).

**Comment by c4710n** [comment]
@jasonjckn You disabled nativeComp, so it works for you. 

Maybe, you can try to enable it.

**Comment by jasonjckn** [comment]
works fine with it enabled

**Comment by jasonjckn** [comment]
https://github.com/nix-community/emacs-overlay/pull/270

**Comment by c4710n** [comment]
@jasonjckn Thanks.
