### ISSUE TITLE
Enable tree-sitter on all Emacs variants built from HEAD.

### ISSUE THREAD

**Issue by thblt** [nix-community/emacs-overlay#265]
Tree-sitter has been merged in `master`, I believe it would make sense that all packages built from master enable it by default.  If it's too soon, maybe some new variants could be created, eg `emacsPgtkNativeCompTreeSitter` and so on?

Best,

**Comment by leungbk** [comment]
The remaining obstacle right now is https://github.com/nix-community/emacs-overlay/issues/258.

**Comment by thblt** [comment]
Right, indeed. But that doesn't prevent creating a new variant `emacsPgtkNativeCompTreeSitter`, that would work at least in Linux?

**Comment by leungbk** [comment]
OK, it's done.
