### ISSUE TITLE
Elpa packages have not been updated since 11/14

### ISSUE THREAD

**Issue by accelbread** [nix-community/emacs-overlay#266]
The elpa package set has not been updated for 13 days (See https://github.com/nix-community/emacs-overlay/tree/master/repos/elpa).

**Comment by antifuchs** [comment]
This just hit me too, as the corfu-doc package (from melpa) has started issuing warnings that its functionality is deprecated by corfu internals (from ELPA).

**Comment by antifuchs** [comment]
Investigating this a bit, looks like emacs-overlay's elpa update action uses the update-elpa script from nixpkgs, which in turn layers on top of https://github.com/nix-community/emacs2nix's elpa-packages.sh. 

It looks like [updating elpa packages is failing](https://github.com/nix-community/emacs-overlay/actions/runs/3572235857/jobs/6004895746#step:6:1929):

```
error: Function called without required argument "cl-print" at /home/runner/work/emacs-overlay/emacs-overlay/repos/elpa/elpa-generated.nix:1439

       … while evaluating 'callPackageWith'

       at /nix/store/yvmp26qw2hrai2kbrvn4qzc89yp6lp9r-source/lib/customisation.nix:120:35:

          119|   */
          120|   callPackageWith = autoArgs: fn: args:
             |                                   ^
          121|     let

       … from call site

       at /nix/store/yvmp26qw2hrai2kbrvn4qzc89yp6lp9r-source/pkgs/applications/editors/emacs/elisp-packages/elpa-packages.nix:48:33:

           47|     imported = import generated {
           48|       callPackage = pkgs: args: self.callPackage pkgs (args // {
             |                                 ^
           49|         inherit fetchurl;

       … while evaluating 'callPackage'

       at /nix/store/yvmp26qw2hrai2kbrvn4qzc89yp6lp9r-source/pkgs/applications/editors/emacs/elisp-packages/elpa-packages.nix:48:27:

           47|     imported = import generated {
           48|       callPackage = pkgs: args: self.callPackage pkgs (args // {
             |                           ^
           49|         inherit fetchurl;

       … from call site

       at /home/runner/work/emacs-overlay/emacs-overlay/repos/elpa/elpa-generated.nix:1439:17:

         1438|       }) {};
         1439|     el-search = callPackage ({ cl-print
             |                 ^
         1440|                              , elpaBuild
```

That doesn't get noticed because [in the update script here](https://github.com/nix-community/emacs-overlay/blob/master/update#L5), a non-0 exit code means "nothing changed"... which is kinda true, but might use a bit more nuance.

**Comment by antifuchs** [comment]
Further update, I could update the elpa repo from a machine running nixos release-22.05. Wonder if unstable (which the CI [workflow installs](https://github.com/nix-community/emacs-overlay/blob/b152560f00867f85c441a2b2981f7ab4b787194e/.github/workflows/ci.yml#L20)) is currently in bad shape...

**Comment by accelbread** [comment]
So seems the cl-print arg is added for a whole bunch of packages in the generated file, I'm guessing since those packages declare cl-print as a dep? I haven't looked at the stuff that does the generating yet

**Comment by accelbread** [comment]
I checked a few other packages that are built-in, and all are either not on elpa at all or are both in index and on their own page.

Since cl-print has a page, maybe its an elpa bug that its not in index?

**Comment by accelbread** [comment]
I found: https://github.com/nix-community/emacs2nix/blob/master/src/Distribution/Nix/Builtin.hs

**Comment by accelbread** [comment]
Not too familiar with Haskell but seems that is a list of built-in packages that does not have cl-print; perhaps just needs to be added there

**Comment by leungbk** [comment]
`nixos-unstable` channel now contains https://github.com/nixos/nixpkgs/commit/6dbbe21770853556e7f48abdc1bf2e1648492c07, so the updates should work again.

The diff of your PR looks good, though I don't have merge privileges in the `emacs2nix` repo.

**Comment by accelbread** [comment]
Thanks, since that solves the issue as far as this repo is concerned, I'll close this issue, and leave the PR up on emacs2nix
