### ISSUE TITLE
Emacs 30 is now master; no packages tracking v29 (I think?)

### ISSUE THREAD

**Issue by YellowOnion** [nix-community/emacs-overlay#269]
Looks like v29 has been forked, and the package `PgtkNativeComp` is tracking the wrong branch.

**Comment by adisbladis** [comment]
The native comp build is _not_ tracking the wrong branch (yet).
While upstream has branched off for release they still haven't tagged a release.

Once a release has been tagged we'll change the native comp derivation to point to that.
