### ISSUE TITLE
[HELP] Trying Emacs 29 pre release

### ISSUE THREAD

**Issue by SohamG** [nix-community/emacs-overlay#275]
Is there any easy way for me to try the Emacs 29 branch with this overlay? I see the git rev is hardcoded in a JSON file.

**Comment by leungbk** [comment]
First, is there any reason you can't use Emacs 30? At the time of writing, it barely differs from 29.

I proposed https://github.com/nix-community/emacs-overlay/issues/271#issuecomment-1336055247 to allow us to fetch the latest `origin/emacs-[0-9]+` branch so that we can have an Emacs 29 without having to wait for 29.0.91 to come out. I'm not sure what the maintainer thinks about this idea though.

**Comment by jasonjckn** [comment]
using flake, just override src attr 

e.g.

overlays  =
``` 
  inputs.emacs-overlay.overlays.default

  (final : prev: {
    emacsPgtk = prev.emacsGit.overrideAttrs
      (old : {
        name = "emacs-pgtk";
        version = inputs.emacs-src.shortRev;
        src = inputs.emacs-src;
        withPgtk = true;
       });
  })

```

inputs = 
```
    emacs-overlay.url = "github:Nix-Community/emacs-overlay";
    emacs-src.url = "github:emacs-mirror/emacs/emacs-29";
```
```

**Comment by mekeor** [comment]
here's a full example for @jasonjckn's advice to use nix' flakes; for mac os.

```console
$ mkdir ~/foo
$ cat > ~/foo/flake.nix << EOF
{
  inputs.emacs-overlay.url = "github:Nix-Community/emacs-overlay";
  inputs.emacs29-src.url = "github:emacs-mirror/emacs/emacs-29";
  inputs.emacs29-src.flake = false;

  outputs = { self, emacs-overlay, emacs29-src, nixpkgs }:
    let
      pkgs = import nixpkgs {
	system = "x86_64-darwin";
	overlays = [
	  emacs-overlay.overlays.default	    
	  (final : prev: {
	    emacs29 = prev.emacsGit.overrideAttrs (old : {
	      name = "emacs29";
              version = emacs29-src.shortRev;
              src = emacs29-src;
              withPgtk = true;
	    });
	  })
	];
      };
    in
      rec {
	defaultPackage.x86_64-darwin = pkgs.emacsWithPackagesFromUsePackage {
	  config = /Users/username/.emacs.d/configuration.org;
	  defaultInitFile = false;
	  package = pkgs.emacs29;
	  alwaysEnsure = true;
	  alwaysTangle = true;	
	};
      };
}
EOF
$ nix --extra-experimental-features "nix-command flakes" profile install --impure ~/foo
```

you may also be able to use [github:numtide/flake-utils' eachDefaultSystem](https://github.com/numtide/flake-utils#eachdefaultsystem---system---attrs) instead of specifying the system manually, i guess.

**Comment by SohamG** [comment]
Oh, thanks jason and mekeor! I need to work on my Nix-Fu

**Comment by rossabaker** [comment]
I just figured out why I've been having a bad time.  Every week when I update my flake, the build hangs on seq-2.23, which I traced to an infinite loop in native compilation of its tests.  But we don't want the ELPA version at all!  There is [logic to avoid the ELPA version if emacs >= 27](https://github.com/NixOS/nixpkgs/pull/74936/files).  Setting the version to just `shortRev` defeats this check.  Once I set the version to start with `29.`, everything is happy again: 

```nix
prev.emacsGit.overrideAttrs (old: {
  name = "emacs29";
  version = "29.0-${inputs.emacs-src.shortRev}";
  src = inputs.emacs-src;
})
```

**Comment by mekeor** [comment]
2023-01-09 15:28 ***@***.***:

> I just figured out why I've been having a bad time. Every week 
> when I update my flake, the build hangs on seq-2.23, which I 
> traced to an
> infinite loop in native compilation of its tests. But we don't 
> want the ELPA version at all! There is logic to avoid the ELPA 
> version if emacs
> >= 27. Setting the version to just shortRev defeats this 
> >check. Once I set the version to start with 29., everything is 
> >happy again:
>
> prev.emacsGit.overrideAttrs (old: {
>   name = "emacs29";
>   version = "29.0-${inputs.emacs-src.shortRev}";
>   src = inputs.emacs-src;
> })

Thank you so much for investigating this! I have been really 
frustrated by this issue. The workaround works for me too; I feel 
relieved.
