### ISSUE TITLE
"Language’s ABI is too new" error in tree-sitter

### ISSUE THREAD

**Issue by twhththt** [nix-community/emacs-overlay#278]
I added the following to my home-manager configuration
```
home.packages = with pkgs; [
  ((emacsPackagesFor emacsGit).withPackages (epkgs: [
    epkgs.tree-sitter
    epkgs.tree-sitter-langs
  ]))
];
```
and init.el
```
  (require 'tree-sitter)
  (require 'tree-sitter-langs)
  (global-tree-sitter-mode)
  (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)
```
However, when I enable tree-sitter-mode in a CPP file, I got this error
```
tree-sitter-load: Language’s ABI is too new: 14, (13 . 13), "/nix/store/ssqrcpzj63xjsm4z4sam42vvkh9m1gsj-emacs-tree-sitter-grammars/langs/bin/cpp.so"
```
Looks like some of the packages are not built with the same toolchain. Any idea on how to solve this problem?

**Comment by twhththt** [comment]
found out the reason: https://github.com/emacs-tree-sitter/elisp-tree-sitter/issues/247

**Comment by twhththt** [comment]
It seems that pinning tree-sitter-cpp with 0.19 is difficult because the generated code is checked in: https://github.com/tree-sitter/tree-sitter-cpp/commit/88ad63bba19b5963e74323030bfd038ef93192de

**Comment by necrophcodr** [comment]
@twhththt I realize this is closed, but the issue appears to persist. Is the "solution" today to simply not use tree-sitter then?

**Comment by willbush** [comment]
@necrophcodr I ran into the same issue. After searching around I think the simplist solution
is to use Emacs 29+ and use the built in tree-sitter. Note that in Emacs 29 the
naming convention is `treesit` for symbols (variables and functions).

Here is the commit I made updating my config:
https://github.com/willbush/system/commit/77a99fa9a3a84cd833d140fa8c4e9c5068ebef27

links I found useful:

https://git.savannah.gnu.org/cgit/emacs.git/tree/admin/notes/tree-sitter/starter-guide?h=feature/tree-sitter
https://github.com/renzmann/treesit-auto
https://www.masteringemacs.org/article/how-to-get-started-tree-sitter
https://robbmann.io/posts/emacs-treesit-auto/
https://archive.casouri.cc/note/2023/tree-sitter-in-emacs-29
