### ISSUE TITLE
Initialize with packages in headers from package and tests 

### ISSUE THREAD

**Issue by psionic-k** [nix-community/emacs-overlay#283]
Within a well-formed elisp package, we know where all the headers are.  If all requirments for the package and its tests are in headers, there's no need to update nix expressions manually after adding new package-requires information.

Probably I can implement this.  Stop me if there's a better solution.

**Comment by akirak** [comment]
@psionic-k AFAIK this has been already done. See `recipes-archive-melpa.json`. There is `deps` field, and it's automatically generated by a script. You can find the scripts in `pkgs/applications/editors/emacs/elisp-packages` in nixpkgs. Except for manual packages, it's automated.

**Comment by psionic-k** [comment]
@akirak  I should have mentioned `emacsWithPackagesFromUsePackage`.  It looks super close to what I need.  I'm not sure.

Use case is for CI, so I need to discover the elisp files within the package repository.

The repo motivating this issue:
https://github.com/positron-solutions/elisp-repo-kit/tree/finish-first-release

**Comment by adisbladis** [comment]
I am closing all issues that looks unrelated to the overlay itself.
Issues reported here should only be pertaining to the overlay infrastructure.

Build issues, runtime issues & the like should be reported to nixpkgs, where this code actually lives.
