### ISSUE TITLE
Is Xcode required for emacsGit on Darwin?

### ISSUE THREAD

**Issue by rossabaker** [nix-community/emacs-overlay#286]
I'm trying to build emacsGit without an xcode installation on aarch64-darwin:

```console
$ nix build -L .#emacsGit
warning: Git tree '/private/tmp/emacs-overlay' is dirty
tree-sitter-grammars> xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
error: builder for '/nix/store/ns9xz4xa545g6dcsmcwlwp0g9whfni01-tree-sitter-grammars.drv' failed with exit code 1;
```

It comes from the `/usr/bin/install_name_tool` call: https://github.com/nix-community/emacs-overlay/blob/a201dcf3d712cf6d3934b396d523041781ff9589/overlays/emacs.nix#L86-L88

Is it expected that we should install Xcode, or does this show that solution is "not kosher"?  Thanks!

<details>
<summary>
System info
</summary>

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.2.0, macOS 13.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
</details>

**Comment by jasonjckn** [comment]
Yah, you basically write it all out above. 

It's required, and not kosher.
