### ISSUE TITLE
Native-comp branch

### ISSUE THREAD

**Issue by spacekitteh** [nix-community/emacs-overlay#29]
It would be great to have a package for the feature/native-comp branch!

**Comment by adisbladis** [comment]
There has been some work towards this in nixpkgs:
- https://github.com/NixOS/nixpkgs/pull/87157
- https://github.com/NixOS/nixpkgs/issues/87400

@bhipple has something experimental in his NUR repo that'll end up in the overlay.

**Comment by bhipple** [comment]
We need to wait for the current Nixpkgs `staging -> master` cycle to go through to get `libgccjit`, but in the meantime if you checkout the `staging` branch you can build it with this expression:

https://github.com/bhipple/nur-packages/blob/master/pkgs/gccemacs/default.nix

Once Nixpkgs `master` is ready, I'll look to send this upstream to the `emacs-overlay`.

**Comment by spacekitteh** [comment]
When would that be?

**Comment by adisbladis** [comment]
`libgccjit` has now hit unstable.
