### ISSUE TITLE
nongnu packages are not in top-level epkgs

### ISSUE THREAD

**Issue by accelbread** [nix-community/emacs-overlay#292]
The packages overlay adds the nongnu packages under the nongnuPackages attr of the emacs packages set, but does not affect its top-level, unlike the other three package sources.

Reproduction sample:
```nix
let pkgs = import nixpkgs-unstable { inherit system; overlays = [ emacs-overlay.overlays.default ]; }; in
(pkgs.emacsPackagesFor pkgs.emacsPgtk).emacsWithPackages (epkgs: with epkgs; [ eat ])
```
This does not work as `eat` is only in nongnuPackages.

**Comment by accelbread** [comment]
I see nongnu is special-cased in the package overlay. I assume making it not special cased would fix the issue.

If that would be acceptable, I can make a PR.

**Comment by leungbk** [comment]
> I see nongnu is special-cased in the package overlay. I assume making it not special cased would fix the issue.
> 
> If that would be acceptable, I can make a PR.

Sounds good, please PR.
