### ISSUE TITLE
Changes in `melpaPackages.emacsql` and `melpaPackages.emacsql-sqlite`

### ISSUE THREAD

**Issue by dschrempf** [nix-community/emacs-overlay#298]
This is actually a problem in Nixpkgs, but it surfaced because of the use of the `emacs-overlay`. So I thought I first report it here.

Recently, the `emacsql` package distributed on MELPA was changed to also include the various `sqlite` backends. For reference, see https://github.com/melpa/melpa/commit/4872ef038dbbf67008bfa7951574ee372d6ff68d.

This leads to errors of the form `(error "No EmacSQL SQLite binary available, aborting")`, because the Nixpkgs derivation of `emacsql` does not build the newly distributed backends.

At the moment, with Nixpkgs, these binaries are built, for example, within `emacsql-sqlite` only. Now, when using the new `emacsql` package, these binaries are not found (because they are expected to be within the `emacsql` directory, and not the `emacsql-sqlite` directory. (Not sure if I explain myself).

The solution is to update MELPA on Nixpkgs AND add builder(s) in Nixpkgs for the sqlite packages to `emacsql`, but that's a bit over the top of my head, at least at the moment.

Any comments?

### Steps To Reproduce
Try to run `magit` with `forge`, or `org-roam` with newest MELPA packages in Emacs using the `emacs-overlay` with `melpaPackages.emacsql` and `melpaPackages.emacsql-sqlite`.

**Comment by wildsebastian** [comment]
Thank you for your analysis @dschrempf! I had the same issue, but not the time to investigate further.
The latest changes [here](https://github.com/melpa/melpa/commit/2e40e3364a5dec38672753093c28ae97d85de189) fixed the behavior in a way that emacs compiles the binary itself.
I am going to create a PR for nixpkgs based on [this commit](https://github.com/wildsebastian/nixpkgs/tree/emacs-fix-emacsql).
In the meanwhile, you can add this to your extra packages:
```
(epkgs.emacsql.overrideAttrs (old: {
  buildInputs = old.buildInputs ++ [ pkgs.sqlite ];

  postBuild = ''
    cd source/sqlite
    make
    cd -
  '';

  postInstall = (old.postInstall or "") + "\n" + ''
    install -m=755 -D source/sqlite/emacsql-sqlite \
      $out/share/emacs/site-lisp/elpa/emacsql-${old.version}/sqlite/emacsql-sqlite
  '';

  stripDebugList = [ "share" ];
}))
```

**Comment by adisbladis** [comment]
As this is fixed in nixpkgs it can be closed.
