### ISSUE TITLE
Update of repos/emacs seem to have stopped 

### ISSUE THREAD

**Issue by terlar** [nix-community/emacs-overlay#30]
It seems repos/emacs haven’t been updated since May 13. 

Usually it is updated every day or several times every day.

I noticed as there is a bug in the current revision tracked by emacs-overlay which is fixed on the later versions. I am not entirely sure how this auto-update works or if there is any logs anywhere to debug this. So just bringing this up to your attention.

**Comment by collares** [comment]
```
patching file lisp/net/tramp-gvfs.el
Hunk #1 FAILED at 125.
1 out of 1 hunk FAILED -- saving rejects to file lisp/net/tramp-gvfs.el.rej
builder for '/nix/store/ig3nzg7ss8sy3m1hn1s0ipz8d7fb4cpq-emacs-git-20200520.0.drv' failed with exit code 1
cannot build derivation '/nix/store/5pxdb21hjvfiwxs7m2vljyqp99ilm8gd-emacs-git-with-packages-20200520.0.drv': 1 dependencies couldn't be built
```

**Comment by adisbladis** [comment]
Closed in https://github.com/nix-community/emacs-overlay/commit/95e7ba3abd507a911e626d15bc89cac5a4b98157
