### ISSUE TITLE
Huge cursor size with display scaling factor >2

### ISSUE THREAD

**Issue by realcomplex** [nix-community/emacs-overlay#300]
This is part bug report, part support request. Using the this emacs overlay I'm suffering from https://gitlab.gnome.org/GNOME/gtk/-/issues/5567 (see also the related https://gitlab.gnome.org/GNOME/gtk/-/issues/5379) which is a regression introduced by gtk3 v3.24.35. It looks like the fix is in gtk4 but unfortunately won't be backported to gtk3 (for now at least).

I am using `emacsPgtk` on Wayland / Fedora 37.

Would it possible to adapt this overlay to use e.g. gtk3 v3.24.34? If not for everyone, then at least is there a way that I can do this? I don't mind not getting cached builds from cachix anymore in that case.

I think I understand nix well enough to figure that changing a dependency version for a single package should be "easy" (kind of the thing that nix is made for), but I'm clueless where to start on actually doing using this overlay flake.

Thanks in advance for the help!

**Comment by jboyens** [comment]
I goofed with this a bit this evening. GTK3 is a complex build. 

3.24.35 had a missing meson build file that they caught in the next commit: https://gitlab.gnome.org/GNOME/gtk/-/commit/b2ad8d2abafbd94c7e58e5e1b98c92e6b6fa6d9a

3.24.36 seems to be what my (nixos-unstable) branch is already built against: 
```
~ λ ldd /nix/store/5g02ryw0japnpvzlzjbvn94b0yg90xc2-emacs-pgtk-20230228.0/bin/emacs
	linux-vdso.so.1 (0x00007ffd22b1c000)
	libgtk-3.so.0 => /nix/store/0z70flbcxfvkp3qap9jdbi6mjjadwwkx-gtk+3-3.24.36/lib/libgtk-3.so.0 (0x00007fd65c800000)
```

I see that the update to this 3.24.36 version hit `staging-next` roughly late-Jan and release-22.11 shows 3.24.35 (w/ the missing meson file patched) as the current revision.

All signs point to the fact that you ought to have your emacs built against at least this version already.

**Comment by adisbladis** [comment]
I am closing all issues that looks unrelated to the overlay itself.
Issues reported here should only be pertaining to the overlay infrastructure.

Build issues, runtime issues & the like should be reported to nixpkgs, where this code actually lives.
