### ISSUE TITLE
bug: called without required argument "melpaBuild"

### ISSUE THREAD

**Issue by eyJhb** [nix-community/emacs-overlay#303]
Just updated my system, and I get the following error

> error: Function called without required argument "melpaBuild" at /nix/store/yxmnq8c07f39iqmhzyqgd2ppfv74dvrf-nixos/nixos/pkgs/applications/editors/emacs/elisp-packages/manual-packages/tsc/default.nix:3

My nixpkgs version is 

```
> nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'                                                                                                                                                                                 
"23.05pre460839.b6cc2f2979a"
```

And I am on the latest overlay revision d89c71d82edf170629279d731e0772feb5037f4c

Hope someone can help :)

**Comment by leungbk** [comment]
Are you still observing this error? If so, can you post some reproducer?

BTW, if you're using the overlay anyway, consider using the tree-sitter modes in upstream Emacs.

**Comment by eyJhb** [comment]
I think it was fixed with updating my nixpkgs version :) Thanks for reminding me to close this issue.
