### ISSUE TITLE
The xeft package and its shared library

### ISSUE THREAD

**Issue by acowley** [nix-community/emacs-overlay#307]
The `xeft` package needs to build a shared library linking with `xapian`. What is the right way to package this between `nixpkgs` and this overlay?

**Comment by jian-lin** [comment]
An example: https://github.com/NixOS/nixpkgs/blob/45c671173b3392e946dee7f9aa6c40c6f348bec3/pkgs/applications/editors/emacs/elisp-packages/elpa-packages.nix#L90

**Comment by adisbladis** [comment]
Thanks @jian-lin! 
This is a nixpkgs issue.
