### ISSUE TITLE
[Q] Would make sense wrap PGtk variants as Gnome Apps (`wrapGAppsHook`)?

### ISSUE THREAD

**Issue by uningan** [nix-community/emacs-overlay#309]
I have an emacs integrated with some theme settings using `gsettings` or wide-system installed cursors. It works perfectly.

But now I'm trying to daemonize it running as a service with `home-manager` module. Then I discovered that GTK environment quirks are not available to `emacs`. Sure, I could wrap it myself. But the question is: assuming you are using `emacsPgtk` variant would make sense build with `wrapGAppsHook` by default or optional?

Regards.

**Comment by uningan** [comment]
Well, I dig upstream and I have found:

```nix
nativeBuildInputs = 
    (omitted)
    ++ lib.optional (withX && (withGTK3 || withXwidgets)) wrapGAppsHook;
```

Seems to have X enabled is a condition to wrap. I think this is imprecise because GApp must be graphical server agnostic (I'm using a lot of wrapped GApps in Wayland).

What do you propose to solve it upstream? I could make a PR but I always feel hard it be accepted.

**Comment by adisbladis** [comment]
Dealt with upstream in https://github.com/NixOS/nixpkgs/pull/224125
