### ISSUE TITLE
jinx package missing dependency

### ISSUE THREAD

**Issue by alanpearce** [nix-community/emacs-overlay#321]
The package [jinx](https://github.com/minad/jinx) has a native module which requires enchant and therefore fails to build correctly (somehow failing silently and causing the Emacs package to report that there are no dictionaries).

I was able to fix this in a personal overlay as below, but I was wondering how we might best get that to work inside emacs-overlay?

```nix
  nixpkgs.overlays = [
    (self: super: {
      emacsPackages.jinx = (super.emacsPackages.jinx.overrideAttrs (oldAttrs: {
        packageRequires = oldAttrs.packageRequires ++ [ pkgs.enchant ];
      }));
    })
  ];
```

**Comment by leungbk** [comment]
Are you on the `nixos-unstable` channel? It is accounted for there (https://github.com/nixos/nixpkgs/blob/457e8b804b35087e467158802c0661a585bfd74d/pkgs/applications/editors/emacs/elisp-packages/elpa-packages.nix#L116), whereas on the `22.11` channel, no such overrides exist.

**Comment by alanpearce** [comment]
I'm on a flake with my nixpkgs input as db24d86dd8a47, which clearly includes the [override](https://github.com/NixOS/nixpkgs/blob/db24d86dd8a4769c50d6b7295e81aa280cd93f35/pkgs/applications/editors/emacs/elisp-packages/elpa-packages.nix), but it still doesn't work without my overlay. I then thought it could be that maybe I should use the elpa version, as that's what the nixpkgs override works on.

Now I can't get it to work again at all, maybe it was just a fluke.

**Comment by leungbk** [comment]
Would you explain how to reproduce the following:

> therefore fails to build correctly (somehow failing silently and causing the Emacs package to report that there are no dictionaries).

I have tried building using commit `cbca5fd577779cbb9228bcdc65474b8cdfe61a2e` of the Emacs overlay (the latest commit, trying with each of `emacsGit` and `emacsUnstable`) and, for nixpkgs, each of `db24d86dd8a4769c50d6b7295e81aa280cd93f35` and `0d9d4e984ed4dbac5428abc9ca62b7e3808ac412` (the latter being the latest `master` at the time of writing). When I enter the `*scratch*` buffer within an `emacs -q` session and enable `global-jinx-mode`, I see that an obviously-misspelled string like `"chexing"` gets highlighted by `jinx`, and that a correctly spelled word does not get highlighted. I have not needed to use your additional override to get my example to work. I don't use `jinx`, so there's probably something I'm missing.

**Comment by alanpearce** [comment]
Hmm, it works in `emacs -q`. Must be in my config then!

**Comment by alanpearce** [comment]
For anyone seeing this in the future: turns out it *always* works if I launch Emacs from a terminal (but not from Finder, Spotlight or Raycast), so my config isn't the issue, but then neither is the module dependency 🤷
