### ISSUE TITLE
Build fails with error about libgenerated.nix

### ISSUE THREAD

**Issue by strobe** [nix-community/emacs-overlay#322]
tried to build my usual config with
[nix-doom-emacs](https://github.com/nix-community/nix-doom-emacs) and https://github.com/nix-community/emacs-overlay/archive/master.tar.gz (nothing changed for few weeks, and last time were no issues)

and got this error:

```
error: attribute 'codeberg' missing for call to 'getAttr'

       at /nix/store/aaghjswwb05hlbc5dgxvka0swdcib0g7-nixos/nixos/pkgs/applications/editors/emacs/elisp-packages/libgenerated.nix:10:33:

            9|                         , commit
           10|                         , ...}: {
             |                                 ^
           11|       github = self.callPackage ({ fetchFromGitHub }:
(use '--show-trace' to show detailed location information)
```

and looks like 2.11 doesn't has codeberg 
https://github.com/NixOS/nixpkgs/blob/21.11/pkgs/applications/editors/emacs/elisp-packages/libgenerated.nix 

but master has

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/elisp-packages/libgenerated.nix#L54

(seems not a nix-doom-emacs issue, see https://github.com/nix-community/nix-doom-emacs/issues/424)

**Comment by leungbk** [comment]
> and looks like 2.11 doesn't has codeberg
https://github.com/NixOS/nixpkgs/blob/21.11/pkgs/applications/editors/emacs/elisp-packages/libgenerated.nix

Why are you on 21.11? Numerous MELPA packages in newer revisions of the overlay use the `codeberg` fetcher. If you want to use these packages, you should update to a version of NixOS that has the `codeberg` fetcher (22.11 ought to be okay).

**Comment by strobe** [comment]
I actually on 22.11
```
> nixos-version
22.11.20230430.db1e4ee (Raccoon)

> nix-info -m
 - system: `"aarch64-linux"`
 - host os: `Linux 6.2.13, NixOS, 22.11 (Raccoon), 22.11.20230430.db1e4ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos"`
 - channels(evgeniy): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

> sudo nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
```

**Comment by leungbk** [comment]
Please post a reproduction recipe. I cannot find any issues using `22.11` when I try to use the overlay to build `git-timemachine` alongside Emacs 30.

**Comment by strobe** [comment]
ok, will try

**Comment by strobe** [comment]
seems ```nix-channel --update``` fixed this for me, so most likely it's was issue with my setup.
