### ISSUE TITLE
Why are tree-sitter grammars impacting the build of emacs?

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/emacs-overlay#323]
If I want to add a tree-sitter grammar to Emacs, it feels like the home-manager's code suggests to do something like:

```nix
  pkgs.emacsUnstable.override (old: {
    treeSitterPlugins = (old.treeSitterPlugins
      ++ (with pkgs.tree-sitter-grammars; [ tree-sitter-jsdoc ]));
  })
```

Doing this triggers a new compilation of Emacs. Nevertheless and AFAIU, no line of Emacs source code depend on tree-sitter grammars. So I wouldn't expect Emacs to be recompiled when changing available grammars.

I would instead expect Emacs to find the globally installed tree-sitter grammars using `treesit-extra-load-path`. This requires setting `treesit-load-name-override-list` so Emacs searches for `<lang>.so` instead of `tree-sitter-<lang>.so`.

If we want the user to specify tree-sitter grammars dedicated to Emacs instead of using the global one, we could add something like:

```nix
{
  extraTreeSitterGrammars = tree-sitter: with tree-sitter.grammars; [ tree-sitter-ocaml ];
}
```

or similar and the grammars would be added to `treesit-extra-load-path` without having to recompile Emacs.

**Comment by DamienCassou** [comment]
The discussion in https://github.com/NixOS/nixpkgs/pull/230547 shows an alternative way in recent versions of nixpkgs: create a derivation with tree-sitter grammars placed inside a `lib/` directory and named after what Emacs expects (see Info node "Tree-sitter Language Grammar" from elisp manual. Then add this derivation to the list of Emacs packages.

The code of [nixpkgs Emacs' wrapper.nix](https://github.com/NixOS/nixpkgs/blob/6c209e862e18d6a9d103a80d5fa2443f4e47163e/pkgs/build-support/emacs/wrapper.nix#L177) takes care of settings `treesit-extra-load-path`.

**Comment by idlip** [comment]
Sorry if this is out of context, but does it relate to this issue (https://github.com/nix-community/emacs-overlay/issues/312) also?

I get that error in Pgtk build so..

I see your name whenever i browse something for emacs or nix, Thank you for the contributions for the best of both world!

**Comment by DamienCassou** [comment]
I suggest having a look at https://github.com/NixOS/nixpkgs/pull/230751.

**Comment by DamienCassou** [comment]
Several persons confirmed that the support for tree-sitter grammars in nixpkgs works perfectly. I suggest we delete the corresponding code in emacs-overlay.

**Comment by leungbk** [comment]
> Several persons confirmed that the support for tree-sitter grammars in nixpkgs works perfectly. I suggest we delete the corresponding code in emacs-overlay.

Done.
