### ISSUE TITLE
build error / regression in the sha from a few hours ago (?)

### ISSUE THREAD

**Issue by jasonjckn** [nix-community/emacs-overlay#327]
Did something change recently, i'm getting this error as of git sha 509a7ef0ea8d63fac38a09f68fde3f4fe8678c92

 nix --version
nix (Nix) 2.15.0

MacOS/Darwin aarch64 

nix build --refresh --recreate-lock-file ~/nix/darwin\#darwinConfigurations.${NIX_HOSTNAME}.system --show-trace
error:
       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'darwin-system-22.11.20230530.9af373a+darwin4.b8c286c'
         whose name attribute is located at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/pkgs/stdenv/generic/make-derivation.nix:270:7

       … while evaluating attribute 'activationScript' of derivation 'darwin-system-22.11.20230530.9af373a+darwin4.b8c286c'

         at /nix/store/i2d6fwnp1n4r2cnncvix93pai3pz3prs-source/modules/system/default.nix:77:7:

           76|
           77|       activationScript = cfg.activationScripts.script.text;
             |       ^
           78|       activationUserScript = cfg.activationScripts.userScript.text;

       … while calling 'g'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/attrsets.nix:417:19:

          416|           g =
          417|             name: value:
             |                   ^
          418|             if isAttrs value && cond value

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/attrsets.nix:420:20:

          419|               then recurse (path ++ [name]) value
          420|               else f (path ++ [name]) value;
             |                    ^
          421|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:270:72:

          269|           # For definitions that have an associated option
          270|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          271|

       … while evaluating the option `system.activationScripts.script.text':

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:743:28:

          742|         # Process mkMerge and mkIf properties.
          743|         defs' = concatMap (m:
             |                            ^
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/i2d6fwnp1n4r2cnncvix93pai3pz3prs-source/modules/system/activation-scripts.nix':

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:744:137:

          743|         defs' = concatMap (m:
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          745|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:815:25:

          814|   */
          815|   dischargeProperties = def:
             |                         ^
          816|     if def._type or "" == "merge" then

       … while calling 'g'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/attrsets.nix:417:19:

          416|           g =
          417|             name: value:
             |                   ^
          418|             if isAttrs value && cond value

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/attrsets.nix:420:20:

          419|               then recurse (path ++ [name]) value
          420|               else f (path ++ [name]) value;
             |                    ^
          421|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:270:72:

          269|           # For definitions that have an associated option
          270|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          271|

       … while evaluating the option `system.activationScripts.applications.text':

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:743:28:

          742|         # Process mkMerge and mkIf properties.
          743|         defs' = concatMap (m:
             |                            ^
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/i2d6fwnp1n4r2cnncvix93pai3pz3prs-source/modules/system/applications.nix':

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:744:137:

          743|         defs' = concatMap (m:
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          745|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:815:25:

          814|   */
          815|   dischargeProperties = def:
             |                         ^
          816|     if def._type or "" == "merge" then

       … while evaluating derivation 'system-applications'
         whose name attribute is located at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/pkgs/stdenv/generic/make-derivation.nix:270:7

       … while evaluating attribute 'passAsFile' of derivation 'system-applications'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/pkgs/build-support/trivial-builders.nix:82:7:

           81|       inherit buildCommand name;
           82|       passAsFile = [ "buildCommand" ]
             |       ^
           83|         ++ (derivationArgs.passAsFile or []);

       … while calling 'g'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/attrsets.nix:417:19:

          416|           g =
          417|             name: value:
             |                   ^
          418|             if isAttrs value && cond value

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/attrsets.nix:420:20:

          419|               then recurse (path ++ [name]) value
          420|               else f (path ++ [name]) value;
             |                    ^
          421|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:270:72:

          269|           # For definitions that have an associated option
          270|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          271|

       … while evaluating the option `environment.systemPackages':

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:765:59:

          764|       if isDefined then
          765|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          766|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while calling 'merge'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/types.nix:491:20:

          490|       check = isList;
          491|       merge = loc: defs:
             |                    ^
          492|         map (x: x.value) (filter (x: x ? value) (concatLists (imap1 (n: def:

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/types.nix:492:35:

          491|       merge = loc: defs:
          492|         map (x: x.value) (filter (x: x ? value) (concatLists (imap1 (n: def:
             |                                   ^
          493|           imap1 (m: def':

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/lists.nix:117:29:

          116|   */
          117|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
             |                             ^
          118|

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/lists.nix:117:32:

          116|   */
          117|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
             |                                ^
          118|

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/types.nix:493:21:

          492|         map (x: x.value) (filter (x: x ? value) (concatLists (imap1 (n: def:
          493|           imap1 (m: def':
             |                     ^
          494|             (mergeDefinitions

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:743:28:

          742|         # Process mkMerge and mkIf properties.
          743|         defs' = concatMap (m:
             |                            ^
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `<unknown-file>':

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:744:137:

          743|         defs' = concatMap (m:
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          745|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/modules.nix:815:25:

          814|   */
          815|   dischargeProperties = def:
             |                         ^
          816|     if def._type or "" == "merge" then

       … from call site

         at /nix/store/pas4fw1s3wvxzqyaqpl2q442hbk72nm9-source/overlays/emacs.nix:91:15:

           90|
           91|   emacsGit = (super.lib.makeOverridable (mkGitEmacs "emacs-git" ../repos/emacs/emacs-master.json) { withSQLite3 = true; withWebP = true; withTreeSitter = true; }).overrideAttrs (
             |               ^
           92|     oa: {

       … while calling 'makeOverridable'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/customisation.nix:70:24:

           69|   */
           70|   makeOverridable = f: origArgs:
             |                        ^
           71|     let

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/customisation.nix:72:16:

           71|     let
           72|       result = f origArgs;
             |                ^
           73|

       … while calling 'mkGitEmacs'

         at /nix/store/pas4fw1s3wvxzqyaqpl2q442hbk72nm9-source/overlays/emacs.nix:3:38:

            2| let
            3|   mkGitEmacs = namePrefix: jsonFile: { ... }@args:
             |                                      ^
            4|     let

       … while calling anonymous lambda

         at /nix/store/pas4fw1s3wvxzqyaqpl2q442hbk72nm9-source/overlays/emacs.nix:15:13:

           14|     builtins.foldl'
           15|       (drv: fn: fn drv)
             |             ^
           16|       super.emacs

       … from call site

         at /nix/store/pas4fw1s3wvxzqyaqpl2q442hbk72nm9-source/overlays/emacs.nix:15:17:

           14|     builtins.foldl'
           15|       (drv: fn: fn drv)
             |                 ^
           16|       super.emacs

       … while calling anonymous lambda

         at /nix/store/pas4fw1s3wvxzqyaqpl2q442hbk72nm9-source/overlays/emacs.nix:19:10:

           18|
           19|         (drv: drv.override ({ srcRepo = true; } // args))
             |          ^
           20|

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/trivial.nix:430:7:

          429|     { # TODO: Should we add call-time "type" checking like built in?
          430|       __functor = self: f;
             |       ^
          431|       __functionArgs = args;

       … while calling anonymous lambda

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/customisation.nix:80:32:

           79|       # Re-call the function but with different arguments
           80|       overrideArgs = copyArgs (newArgs: makeOverridable f (overrideWith newArgs));
             |                                ^
           81|       # Change the result of the function call by applying g to it

       … from call site

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/customisation.nix:80:41:

           79|       # Re-call the function but with different arguments
           80|       overrideArgs = copyArgs (newArgs: makeOverridable f (overrideWith newArgs));
             |                                         ^
           81|       # Change the result of the function call by applying g to it

       … while calling 'makeOverridable'

         at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/lib/customisation.nix:70:24:

           69|   */
           70|   makeOverridable = f: origArgs:
             |                        ^
           71|     let

       error: function 'anonymous lambda' called with unexpected argument 'withTreeSitter'

       at /nix/store/k6m8q20jgza91i25ba943aym53cchsix-source/pkgs/applications/editors/emacs/generic.nix:10:1:

            9| }:
           10| { stdenv, llvmPackages_6, lib, fetchurl, fetchpatch, substituteAll, ncurses, xlibsWrapper, libXaw, libXpm
             | ^
           11| , Xaw3d, libXcursor,  pkg-config, gettext, libXft, dbus, libpng, libjpeg, giflib

my overlay is 

```
﻿﻿{ system, inputs, ... }:

[

  inputs.emacs-overlay.overlays.default

  # -------------------------------------------------------------------------------------------------------

  (final: prev: {

    emacs-29 = (prev.emacsGit.overrideAttrs (old:
      let major = "29";
      in {
        name = "emacs-${major}";
        version = inputs.emacs-src.shortRev;
        src = inputs.emacs-src;
        patches = [
          "${inputs.emacs-plus}/patches/emacs-${major}/system-appearance.patch"
          "${inputs.emacs-plus}/patches/emacs-${major}/no-frame-refocus-cocoa.patch"
          "${inputs.emacs-plus}/patches/emacs-${major}/round-undecorated-frame.patch"
          "${inputs.emacs-plus}/patches/emacs-${major}/fix-window-role.patch"
        ];

        # wasn't this merged into mainline?
        configureFlags = old.configureFlags ++ [
          "--enable-check-lisp-object-type"
          # "--with-native-compilation=aot"
        ];

      })).override {

        stdenv = prev.addAttrsToDerivation {
          NIX_CFLAGS_COMPILE =
            "-mcpu=native -O3 -pipe -ftree-vectorize -fomit-frame-pointer -DFD_SETSIZE=10000 -DDARWIN_UNLIMITED_SELECT";
          BYTE_COMPILE_EXTRA_FLAGS = ''
            --eval '(setq native-comp-speed 3)'
            --eval '(setq native-comp-compiler-options '("-O3" "-ftree-vectorize" "-fomit-frame-pointer"))'
          '';
        } (prev.impureUseNativeOptimizations final.llvmPackages_14.stdenv);

      };

    # -------------------------------------------------------------------------------------------------------

    ;

  })

]

```

**Comment by emeinhardt** [comment]
I get the same error. I believe [this commit](https://github.com/nix-community/emacs-overlay/commit/509a7ef0ea8d63fac38a09f68fde3f4fe8678c92) is the breaking change.

**Comment by leungbk** [comment]
Sorry about that. Would you please confirm #328 addresses your issue?

With the new release, the tree-sitter stuff has been moved to upstream nixpkgs and now requires a dummy Emacs package to be installed to obtain grammars.

**Comment by leungbk** [comment]
>        patches = [
>          "${inputs.emacs-plus}/patches/emacs-${major}/system-appearance.patch"
>          "${inputs.emacs-plus}/patches/emacs-${major}/no-frame-refocus-cocoa.patch"
>          "${inputs.emacs-plus}/patches/emacs-${major}/round-undecorated-frame.patch"
>          "${inputs.emacs-plus}/patches/emacs-${major}/fix-window-role.patch"
>        ];

Unrelated, but I suggest that you also include https://github.com/nix-community/emacs-overlay/blob/f3de842d61a82311589af736888c0bd52e300615/overlays/emacs.nix#L93-L96

**Comment by leungbk** [comment]
OK, so my PR builds on nixpkgs master and doesn't appear to throw on 22.11 (haven't seen the whole build in 22.11), so I went ahead and merged. Let me know if you encounter any further issues.
