### ISSUE TITLE
regression 10 minutes ago

### ISSUE THREAD

**Issue by jasonjckn** [nix-community/emacs-overlay#332]
syntax error @ https://github.com/nix-community/emacs-overlay/blob/master/flake.nix#L81

       error: syntax error, unexpected ';', expecting ')'

       at /nix/store/913f4swl2i42q15jqhxqzf9h54smlsy9-source/flake.nix:81:75:

           80|           "22.11" = mkHydraJobs (importPkgs nixpkgs-stable { inherit system; });
           81|           "unstable" = mkHydraJobs (importPkgs nixpkgs { inherit system; };);
             |                                                                           ^
           82|         };

**Comment by adisbladis** [comment]
Fixed by fe9ad516f6404f8ce5fffd3955a29418eb82347f
