### ISSUE TITLE
Broken due to anonymous function / unexpected argument

### ISSUE THREAD

**Issue by c-wicklein** [nix-community/emacs-overlay#338]
Using nix 2.13.2 on macOS, I noticed this start happening today...

```
error: anonymous function at /nix/store/r7gbaimmp4s8v8d402rvxakm8k8hxsc5-source/pkgs/applications/editors/emacs/generic.nix:10:1 called with unexpected argument 'withTreeSitter'

       at /nix/store/r7gbaimmp4s8v8d402rvxakm8k8hxsc5-source/lib/customisation.nix:72:16:

           71|     let
           72|       result = f origArgs;
             |                ^
           73|
(use '--show-trace' to show detailed location information)
```

I was able to work around the problem by switching from using `https://github.com/nix-community/emacs-overlay/archive/master.tar.gz` as an overlay to a tar ball created from `emacs-overlay` at `b769c7c0e616c238382d3dfe9c8e4cb7fdf3d1a3` (an arbitrary commit from a few days ag which I believed would pre-date the problem.)

**Comment by leungbk** [comment]
Please update your channel.

**Comment by c-wicklein** [comment]
Thank you.

**Comment by c-wicklein** [comment]
I appreciate your suggestion to update my channel, and I wonder if you could confirm my inference that the channel I'm using (Darwin stable at `2dc8a48`, ca. 2023-02-23) includes both Nix source which is package specific and Nix source which is shared across packages (e.g. `lib/customisation.nix` apparently),  so if I use an overlay such as `emacs-overlay` (which BTW I love) at its `HEAD`, then I'm signing up for trouble if don't also keep the channel I'm using at its own `HEAD`?

I've decided to keep `emacs-overlay` pinned at `b769c7c` the the time being to avoid a cascade of change-related problems.  My channel is pinned to `2dc8a48` so that [nix-cl](https://github.com/Uthar/nix-cl) (utilities for packaging Common Lisp libraries) can remain pinned to `4db0ee5` so that my own `deps.nix`-like files don't stop working due to an API change in `nix-cl` sending me off to shave a yak on Tuesday morning.  Sigh.
