### ISSUE TITLE
broken `emacsPackagesFor` on 22.11

### ISSUE THREAD

**Issue by mjhoy** [nix-community/emacs-overlay#339]
It looks like https://github.com/nix-community/emacs-overlay/pull/335 broke `emacsPackagesFor` on 22.11; I now get the error:

```
error: anonymous function at /nix/store/p31hbx4brpibg63fb88wy0g302qxn2sk-nixpkgs-src/pkgs/top-level/emacs-packages.nix:58:53 called with unexpected argument 'elpaDevelPackages'
```

Supporting this argument hasn't been backported yet: https://github.com/NixOS/nixpkgs/pull/237675

Is there a good way for me to provide some kind of shim to get this working in my config? Thanks.

**Comment by leungbk** [comment]
The backport PR has been merged, and I've re-enabled support in the overlay for now, so everything should be fine once the 22.11 channel updates to contain the backport commit.
