### ISSUE TITLE
Org-mode master branch

### ISSUE THREAD

**Issue by walseb** [nix-community/emacs-overlay#340]
Hello!

Is there a clean way to pull `org-mode` from the latest master branch? Currently, it appears to pull from stable releases.

I suppose I could specify the build recipe myself, or override the source repo, but is there a better way to do it, like with the emacs-git package?

Thanks,
Sebastian

**Comment by leungbk** [comment]
We have org-mode from `elpa-devel`: https://github.com/nix-community/emacs-overlay/blob/505bd47eed2d362e7c1540fdfde041388ca67d57/repos/elpa/elpa-devel-generated.nix#L4006-L4010

Is this enough for you?

**Comment by walseb** [comment]
Thank you! 

That's just what I was looking for. So `elpaDevelPackages.org` in nix.
