### ISSUE TITLE
How to install and use tree-sitter grammars?

### ISSUE THREAD

**Issue by okvik** [nix-community/emacs-overlay#341]
I'm trying to figure out how to use the tree-sitter with Emacs on NixOS to no avail.

I've installed `emacs-unstable` as:

```
pkgs.emacs-unstable.override {
        withGTK3 = true;
        withTreeSitter = true;
      };
```

I've additionally installed `tree-sitter` and all of the grammars from `tree-sitter-grammars` in `nixpkgs`. Unfortunately this doesn't seem to work just like that, as Emacs reports the following when trying out a tree-sitter mode:

```
 ■  Warning (treesit): Cannot activate tree-sitter, because language grammar for cpp is unavailable (not-found): (libtree-sitter-cpp libtree-sitter-cpp.0 libtree-sitter-cpp.0.0 libtree-sitter-cpp.so libtree-sitter-cpp.so.0 libtree-sitter-cpp.so.0.0) No such file or directory
```

I can't seem to find any specific instructions or code that is needed to get this to work. Any ideas?

**Comment by leungbk** [comment]
```nix
    let
      myEmacs = (emacsPackagesFor emacs-git).emacsWithPackages (epkgs: with epkgs; [
        vterm
        treesit-grammars.with-all-grammars
      ];
```

**Comment by okvik** [comment]
Works nicely, thank you very much.
