### ISSUE TITLE
Possible to add binary that support `withX` and `withGTK3`? 

### ISSUE THREAD

**Issue by StrictlyMonad** [nix-community/emacs-overlay#347]
Because of the recent introduction of proper frame transparency support in Emacs, the user is now required to compile Emacs with both `withGTK3 = true;` and `withX = true;` toggled. But because this process is time-consuming for low-end hardware, I thought I should ask if it would be possible for the overlay to provide an additional cached binary which support this need.

Obviously, it's perfectly fine if this proposal is rejected since it's going to cost hydra bit of processing power to deliver. But I figured it does not hurt to ask, and therefore I am here asking! :)

**Comment by adisbladis** [comment]
I'm not sure if I think it's valuable enough to add yet another variant to our already quite large list. Especially as the GTK build has issues with Xinput2 that is enabled if you're building Emacs 29 or above.

You can always use the `emacs-gtk` attribute from nixpkgs if this is important to you.

**Comment by adisbladis** [comment]
Look at this thread for more context https://lists.gnu.org/archive/html/emacs-devel/2022-08/msg00752.html.

**Comment by StrictlyMonad** [comment]
Oh, well. Guess I'll use stable Emacs for now.

**Comment by StrictlyMonad** [comment]
Apparently replacing the default value of `--with-x-toolkit` from `lucid` to `no` and adding `--with-cairo` to the compile flags (which it already is part of) should resolve the issue.

Don't know if y'all are interested in this change though.
