### ISSUE TITLE
Consider make `withGTK3 = true` as default?

### ISSUE THREAD

**Issue by eval-exec** [nix-community/emacs-overlay#352]
I think most people prefer GTK instead of lucid.

**Comment by accelbread** [comment]
IIRC, upstream changed the default from GTK to Lucid, since GTK was buggy, and Lucid was a better default. I don't remember exactly, so don't quote me on that.

**Comment by adisbladis** [comment]
> IIRC, upstream changed the default from GTK to Lucid, since GTK was buggy, and Lucid was a better default. I don't remember exactly, so don't quote me on that.

Yeah. GTK is not the default for a reason: https://github.com/NixOS/nixpkgs/pull/189543.
