### ISSUE TITLE
`emacsWithPackagesFromUsePackages { defaultInitFile = true;}` broken

### ISSUE THREAD

**Issue by cmm** [nix-community/emacs-overlay#356]
by https://github.com/NixOS/nixpkgs/pull/253448.

adding a dummy `version = "0.1";` to the definition of `defaultInitFilePkg` fixes this, but I don't know if that's the right way to do this (or if it's the only thing that is broken now).

**Comment by SrEstegosaurio** [comment]
I'm also encountering the same error when having `defaultinitFile = false`.

**Comment by jian-lin** [comment]
Sorry about the break.

> adding a dummy version = "0.1"; to the definition of defaultInitFilePkg fixes this, but I don't know if that's the right way to do this 

Yes, it is the right way.

**Comment by cmm** [comment]
> Sorry about the breakage.
> 
> > adding a dummy version = "0.1"; to the definition of defaultInitFilePkg fixes this, but I don't know if that's the right way to do this 
> 
> Yes, it is the right way.

what I mean is, I guess, is that I'm not quite clear on what problem is being solved by requiring the version field, especially for programmatic derivations

**Comment by jian-lin** [comment]
> for programmatic derivations

You mean derivations like the one for default.el, right?

> what problem is being solved by requiring the version field

A side effect of NixOS/nixpkgs#253448 is to make `version` non-optional, which is the convention of Nixpkgs.

**Comment by jian-lin** [comment]
FYI, https://github.com/nix-community/emacs-overlay/pull/357

**Comment by cmm** [comment]
> You mean derivations like the one for default.el, right?

Er, yeah; a better term would be "synthetic" or something I guess?  Ones where the notion of "version" does not make any sense because there is no independently-changing "upstream".

I guess I just have a problem with having to outright fabricate data to appease bureaucratic conventions. But it's no big deal either way, and thank you for the prompt fix!
