### ISSUE TITLE
outdated .elc

### ISSUE THREAD

**Issue by 0x450x6c** [nix-community/emacs-overlay#360]
Hello, it seems for some packages (magit) the .elc files are outdated.

With latest version (`db6c96d74eb0e60e7e344e81a56b33390e33474d`) of emacs overlay,
when I run `M-x magit-status`, I have following error: `(void-variable magit-section-preserve-visibility)`.

It works fine if I load `magit-section.el`, `magit-status.el`, `magit-diff.el` and `magit-log.el` from `/nix/store/...`.

Is anyone has similar issue?
Any tips?

**Comment by dschrempf** [comment]
I am having similar issures with `embark-act` and Org mode, see https://github.com/oantolin/embark/issues/723#issuecomment-2186639225. Others also had this problem but it seems to be gone for them, while I am still observing the problem. Did you find a solution?

**Comment by dschrempf** [comment]
Adding another potenially related issue: https://github.com/nix-community/emacs-overlay/issues/366, and upstream https://github.com/szermatt/mistty/issues/14#issuecomment-1792965848.

**Comment by adisbladis** [comment]
I am closing all issues that looks unrelated to the overlay itself.
Issues reported here should only be pertaining to the overlay infrastructure.

Build issues, runtime issues & the like should be reported to nixpkgs, where this code actually lives.
