### ISSUE TITLE
Can we confirm that *.elc files are bundled by mistake here ?

### ISSUE THREAD

**Issue by 573** [nix-community/emacs-overlay#366]
nix-repl> :lf github:nix-community/emacs-overlay
nix-repl> :u (lib.x86_64-linux.emacsWithPackagesFromUsePackage { config = ""; extraEmacsPackages = epkgs: [epkgs.mistty];})

`emacs` and therein `M-x mistty` gives

>Symbol’s value as variable is void: mistty-mode-map

[Upstream says](https://github.com/szermatt/mistty/issues/14#issuecomment-1792965848) `mistty` is wrongly packaged.

**Comment by adisbladis** [comment]
The overlay doesn't overwrite the emacs attribute, so this example would use emacs 28.

**Comment by 573** [comment]
Solved see upstream.
