### ISSUE TITLE
extraConfig (in homeManager.emacs) is ignored when using this overlay with a conig.el from path

### ISSUE THREAD

**Issue by thomaslaich** [nix-community/emacs-overlay#367]
When providing `extraConfig` in the emacs program using home manager, the value is ignored when using this overlay.

That is, if I do something like this

```nix
  programs.emacs = {
    enable = true;
    extraConfig = ''
      (load-theme 'kanagawa t)
    '';
    extraPackages = epkgs: [ epkgs.autothemer epkgs.kanagawa-theme ];
    package = (pkgs.emacsWithPackagesFromUsePackage {
      config = ./config.el; #contains my actual emacs config
      package = pkgs.emacs-pgtk;
      ...
    });
    ...
  };
```
then `(load-theme 'kanagawa t)` is not called when starting emacs.

If I do the same with vanilla emacs, then the theme gets applied. That is, if I do this, then the theme gets applied:

```nix
  programs.emacs = {
    enable = true;
    extraConfig = ''
      (load-theme 'kanagawa t)
    '';
    extraPackages = epkgs: [ epkgs.autothemer epkgs.kanagawa-theme ];
    package = pkgs.emacs;
    ...
  };
```

You might ask why I want to provide both `extraConfig` and a `config.el`. The reason is that I want to provide system wide themes using a separate module (see https://github.com/buntec/nix-colorscheme). This way I can switch my theme in one place and it updates tmux, kitty, neovim, emacs, fish, etc. For that I have to provide some extra configuration to emacs to load the theme.

Is this a bug or intended behaviour? It would be perfect for my use case if `default.el` would contain the merged output from `extraConfig` and my `config.el` :)

strangely enough, the packages from `emacs.extraPackages` and `extraEmacsPackages` from this overlay seem to get merged.

My full emacs config here: https://github.com/thomaslaich/nix-config/blob/main/home/emacs/emacs.nix

(I'm very new to nix, so forgive if this is a dumb question/request)

**Comment by emagieika** [comment]
Same issue here. This breaks [stylix](https://github.com/danth/stylix) for me.

**Comment by adisbladis** [comment]
`pkgs.emacsWithPackagesFromUsePackage` returns a wrapped package, and indeed isn't expected to work when passed to home manager.

**Comment by thomaslaich** [comment]
For anyone still coming across this thread, I finally found a workaround here:

https://github.com/danth/stylix/issues/453#issuecomment-2246505113
