### ISSUE TITLE
Potential cache miss when using emacs.pkgs.*

### ISSUE THREAD

**Issue by 573** [nix-community/emacs-overlay#368]
Related to #366 

```nix
let
  emacs = inputs.emacs-overlay.packages.${system}.emacs-unstable-nox;
  pack = allMelpaPackages:
    with allMelpaPackages; [
      mistty
    ];
in {
  programs.emacs = {
      enable = true;
      package = emacs;
      extraPackages = epkgs: with epkgs;
        (pack emacs.pkgs.melpaPackages);
  };
}
```

I figured out a fix for the other issue, but now I have a rebuild instead of a cache hit for my emacs derivation.

Is that to be expected ?

**Comment by acid-bong** [comment]
iirc only packages for the regular `pkgs.emacs` are cached. i moved from it to emacs-gtk and nix rebuilds everything. not related to the overlay
