### ISSUE TITLE
Is it possible to disable the compilation of all the built-in emacs packages ?

### ISSUE THREAD

**Issue by hydrocat** [nix-community/emacs-overlay#369]
Compiling them takes the majority of the `nixos-rebuild switch --upgrade` command.
I am sure that I do not use all the built-in packages so I was thinking that disabling it would be worth it.

Does it make sense to make an overlay of this overlay or maybe add an option to this one instead ?

**Comment by adisbladis** [comment]
You can already disable native compilation with `emacs.override { withNativeCompilation = false; }`.

**Comment by daanturo** [comment]
> You can already disable native compilation with `emacs.override { withNativeCompilation = false; }`.

Using that disables native compilation completely (event run-time JIT) and requires a full rebuild of Emacs, the latter in turn makes `nixos-rebuild` even more costly. Is it possible to affect just packages of `emacsWithPackagesFromUsePackage`? Thank you.

**Comment by jian-lin** [comment]
@daanturo I guess this meets your requirements:

```nix
emacs.overrideAttrs (old: { passthru = old.passthru // { withNativeCompilation = false; }; })
```

However, this relies on implementation details and can stop working in the future.

**Comment by daanturo** [comment]
> emacs.overrideAttrs (old: { passthru = old.passthru // { withNativeCompilation = false; }; })

This is godsend!
