### ISSUE TITLE
Export org to latex and opening them doesn't work

### ISSUE THREAD

**Issue by hmanhng** [nix-community/emacs-overlay#377]
I want to export org to latex and open them in `zathura` with `Cc Ce l o` but it doesn't work.

**To Reproduce**
1. Open simple org file
2. Export to `latex` and open with `C-c C-e l o`
3. It takes about 15-20 seconds to export a file with only 10 lines
4. No applications open with the `pdf` file

~Also I use [app-launcher](https://github.com/SebastienWae/app-launcher]) and found a lot of applications missing~, Only `zathura` was not found.

**Comment by adisbladis** [comment]
I am closing all issues that looks unrelated to the overlay itself.
Issues reported here should only be pertaining to the overlay infrastructure.

Build issues, runtime issues & the like should be reported to nixpkgs, where this code actually lives.
