### ISSUE TITLE
When building with override to release 29.190, `native-comp-driver-options` patch breaks

### ISSUE THREAD

**Issue by psionic-k** [nix-community/emacs-overlay#381]
https://github.com/emacs-mirror/emacs/releases/tag/emacs-29.1.90

Looks like they added some logic for macs and the patch wouldn't apply.

I just did a workaround with early-init for now since I didn't immediately recognize where to update the patch.

My comp.el as it built:
```elisp
(defcustom native-comp-driver-options (append (when (eq system-type 'darwin)
                                                '("-Wl,-w"))
                                              '("-B/nix/store/k5x12wcyiflgidyfkgc7lb09ad0y1sc9-libgccjit-12.3.0/lib" "-B/nix/store/k5x12wcyiflgidyfkgc7lb09ad0y1sc9-libgccjit-12.3.0/lib/gcc" "-B/nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib" "-B/nix/store/7vq9zymw7zk2i0k1i4nfkl6hmlx3gxji-gcc-12.3.0-libgcc/lib" "-B/nix/store/hf2gy3km07d5m0p1lwmja0rg9wlnmyr7-gcc-12.3.0/bin" "-B/nix/store/1alqjnr40dsk7cl15l5sn5y2zdxidc1v-binutils-wrapper-2.40/bin" "-B/nix/store/1fn92b0783crypjcxvdv6ycmvi27by0j-binutils-2.40/bin"))
  "Options passed verbatim to the native compiler's back-end driver.
```

The workaround:
```elisp
(setopt  native-comp-driver-options '("-B/nix/store/k5x12wcyiflgidyfkgc7lb09ad0y1sc9-libgccjit-12.3.0/lib"
                              "-B/nix/store/k5x12wcyiflgidyfkgc7lb09ad0y1sc9-libgccjit-12.3.0/lib/gcc"
                              "-B/nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib"
                              "-B/nix/store/7vq9zymw7zk2i0k1i4nfkl6hmlx3gxji-gcc-12.3.0-libgcc/lib"
                              "-B/nix/store/hf2gy3km07d5m0p1lwmja0rg9wlnmyr7-gcc-12.3.0/bin"
                              "-B/nix/store/1alqjnr40dsk7cl15l5sn5y2zdxidc1v-binutils-wrapper-2.40/bin"
                              "-B/nix/store/1fn92b0783crypjcxvdv6ycmvi27by0j-binutils-2.40/bin"))
```

**Comment by leungbk** [comment]
The patch applies for Emacs 29.1 and 29.1.90 (but not for 30), but is not *being* applied when using an Emacs defined in the overlay since for now, we are setting the `patches` to `[]` and instead performing a `substituteInPlace` for all overlay-defined Emacsen.

I have successfully built the Emacs 29.1.90 provided by the latest revision of the overlay without any modifications, and confirmed in its `comp.el` that the `substituteInPlace` patches the `native-comp-driver-options` as expected. How are you building your Emacs?

**Comment by psionic-k** [comment]
In my flake, I fetch a specific set of source:
```nix
    emacs29-src = {
      url = "github:emacs-mirror/emacs/emacs-29.1.90";
      flake = false;
    };
```
Then when applying the overlay, I just shove the source into a similar Emacs :eyes: 
```nix
    nixpkgs.overlays = [ 
      emacs-overlay.overlays.default
      # Add an explicit source to the flake if you require
      (final : prev: {
        emacs = prev.emacs.overrideAttrs (old: {
          name = "emacs29";
          version = emacs29-src.shortRev;
          src = emacs29-src;
          patches = null;
        });
      })
    ];
```
Pray tell there is a better way? :cat:

**Comment by leungbk** [comment]
> ```nix
>     nixpkgs.overlays = [ 
>       emacs-overlay.overlays.default
>       # Add an explicit source to the flake if you require
>       (final : prev: {
>         emacs = prev.emacs.overrideAttrs (old: {
>           name = "emacs29";
>           version = emacs29-src.shortRev;
>           src = emacs29-src;
>           patches = null;
>         });
>       })

Using `shortRev` here is going to give a `version` that throws off the version check that lives in upstream `nixpkgs` (https://github.com/nixos/nixpkgs/blob/bd645e8668ec6612439a9ee7e71f7eac4099d4f6/pkgs/applications/editors/emacs/make-emacs.nix#L156-L158).

```
nix-repl> lib.versionOlder "d963bc6" "29"
lib.versionOlder "d963bc6" "29"
true
```

I think that is why your build tries to use the Emacs 28 patch.

The Emacsen defined by this overlay are, for now, not using the same patches as upstream `nixpkgs`; we initially set `patches` to `[]` and then override them to a singleton list for Emacs 30.

Since you're not using an overlay-defined Emacs, your installation does not undergo any of the changes that we enforce in the overlay in the `mkGitEmacs` function.

**Comment by leungbk** [comment]
The overlay's `emacs-unstable` attribute provides `29.1.90` at the time of writing.

**Comment by psionic-k** [comment]
Thanks!
