### ISSUE TITLE
overrideScope is deprecated: Error on nixpkgs/23.05

### ISSUE THREAD

**Issue by ashgillman** [nix-community/emacs-overlay#394]
This commit: https://github.com/nix-community/emacs-overlay/commit/b7c67b5f71db89ec27e1aa4413fbbcdf5bbfa451
Relies on: https://github.com/NixOS/nixpkgs/commit/3c1f82f99ee02dad4eb480f6216ae2ece445d11d

This makes the overlays only compatible with 23.11+. Maybe this is intentional, but I didn't see it documented anywhere.

Mostly documenting this so that people can see if they get this error:
```
trace: warning: `overrideScope` (from `lib.makeScope`) is deprecated. Do `overrideScope' (self: super: { … })` instead of `overrideScope (super: self: { … })`. All other overrides have the parameters in that order, including other definitions of `overrideScope`. This was the only definition violating the pattern.
error: infinite recursion encountered
```
And like me, have no idea what they're doing, then they should update to 23.11.

I guess it was about time I caught up to the latest stable release :)

Thanks!
Ash

**Comment by leungbk** [comment]
Thanks for bringing this up. Yeah, I think since the overlay is meant for people who want bleeding-edge Emacs and/or Elisp packages, it's reasonable to expect them to have a recent-ish nixpkgs (23.05 is currently EOL).
