### ISSUE TITLE
Request: jcs-elpa

### ISSUE THREAD

**Issue by bandithedoge** [nix-community/emacs-overlay#398]
https://jcs-emacs.github.io/jcs-elpa/

An ELPA for [jcs-emacs](https://github.com/jcs-emacs/jcs-emacs), an Emacs configuration by [Jen-Chieh Shen](https://github.com/jcs090218). It has a lot of recent and less popular packages.

**Comment by adisbladis** [comment]
I wouldn't want to add a repo to this overlay without adding it to nixpkgs first.
