### ISSUE TITLE
Upload emacs-git packages to cachix

### ISSUE THREAD

**Issue by slotThe** [nix-community/emacs-overlay#399]
Hi,

currently, there are hydra jobs to build packages for [`emacs` and `emacs-unstable`](https://github.com/nix-community/emacs-overlay/blob/master/flake.nix#L80-L81), so that they can be cached and users do not have to rebuild every elisp package themselves. Fast to build as many are, this can otherwise take 3–5 minutes for a moderate number of packages (~200–400).

However, I'd wager a not-insignificant number of users using the overlay are actually building (or, rather, downloading) a more recent build of Emacs, like `emacs-git`. I would therefore advocate for adding at least `packages-git` to the current set of packages that are shipped to cachix.

What do people think?

**Comment by Icy-Thought** [comment]
I most certainly would agree and appreciate this change! Because rebuilding `emacs-git` on my low-end laptop is a rather time-consuming task.

**Comment by adisbladis** [comment]
While it would be great to offer binaries for all variants it causes too much package churn to do so for the git variants.
We'd eat up all available nix-community hydra capacity while also causing eviction of stuff from the cache which is potentially more useful.
