### ISSUE TITLE
Request: remove `use-package` from package list, if Emacs version is >=29

### ISSUE THREAD

**Issue by acid-bong** [nix-community/emacs-overlay#407]
use-package is already embedded in Emacs v29 in its latest version, v2.4.5, there's no need to add it to the generated package list anymore

**Comment by adisbladis** [comment]
I am closing all issues that looks unrelated to the overlay itself.
Issues reported here should only be pertaining to the overlay infrastructure.

Build issues, runtime issues & the like should be reported to nixpkgs, where this code actually lives.
