### ISSUE TITLE
`(void-function internal--without-restriction)` for `consult` under Emacs 30

### ISSUE THREAD

**Issue by adham-omran** [nix-community/emacs-overlay#409]
This was first opened as a discussion on https://github.com/minad/consult/discussions/1042#discussioncomment-9807816

I've started using Emacs 30 under NixOS lately, using the [nix-community/emacs-overlay](https://github.com/nix-community/emacs-overlay), I encountered this error when calling `(consult-imenu)`

The author notes that

> It seems that the byte code of the installed Consult package is outdated

I've made sure to remove both my `eln-cache` and even `elpa` directories and re-run after the rebuild but the issue persisted.

Is there any way to trigger a recompile of everything?

**Comment by adisbladis** [comment]
I am closing all issues that looks unrelated to the overlay itself.
Issues reported here should only be pertaining to the overlay infrastructure.

Build issues, runtime issues & the like should be reported to nixpkgs, where this code actually lives.

**Comment by adham-omran** [comment]
Thank you for clarifying. I'll keep that in mind when reporting issues related to the overlay.
