### ISSUE TITLE
Can my telega packages be added to this overlay?

### ISSUE THREAD

**Issue by ipvych** [nix-community/emacs-overlay#410]
[Telega](https://github.com/zevlg/telega.el) has a native dependency on tdlib which for unstable version usually needs to be matched down to specific commit in tdlib repo and for stable version needs to be locked to specific version usually not available in nixpkgs so I have created my own overlay - https://github.com/ipvych/telega-overlay which has an update script that fetches the right commit for tdlib from dockerfile in telega repo & overrides telega package to use it.

This overlay has been working fine for over a year now and I was thinking of merging it with this overlay so that it can be useful to more people & so that someone more knowledgeable about nix can maintain the nix part of it as I don't know much about it and cant fix issues like https://github.com/ipvych/telega-overlay/issues/2 myself properly.

I can adapt the update script from my repo to this overlay but I may need some help with nix part to make it work.

**Comment by adisbladis** [comment]
Nixpkgs already "pins" the use of stable tdlib. When I was using Telega this was good enough already and had zero maintenance effort.

I feel vary of adding maintenance burden around tdlib in emacs-overlay. It feels like a bad fit.
