### ISSUE TITLE
How to gc previous compilations of emacs-pgtk? 

### ISSUE THREAD

**Issue by sjLambda** [nix-community/emacs-overlay#414]
How do I garbage collect previous emacs-pgtk compilations? I've tried the usual nix-collect-garbage and nix store gc. They do not pick up previous versions of compilations. I see all 10 previous compilations and drv in /nix/store. 

I even tried nix store delete /nix/store/sha256-emacs-pgtk-date. The error I get is "cannot delete path since it is still alive". With --ignore-liveness option, the error I get is "you're not allowed to ignore liveness".

What is the canonical way to get around this? I want to recover some disk space since each compilation is consuming over one GB.

**Comment by adisbladis** [comment]
This question is not related to the overlay. I suggest asking around in general Nix support channels instead.
