### ISSUE TITLE
How can I add isabelle?

### ISSUE THREAD

**Issue by Septias** [nix-community/emacs-overlay#418]
I want to use emacs to develop Isabelle. The official repository provides an example configuration file: https://github.com/m-fleury/isabelle-emacs/blob/Isabelle2024-vsce/src/Tools/emacs-lsp/spacemacs_layers/isabelle/README.org. It looks like it is trying to install some package from GitHub directly, which is why I get  `Emacs package isar-mode, declared wanted with use-package, not found.` Is there a way to install packages directly from GitHub, maybe as a package overwrite?  Or should I ask the author @m-fleury whether he can publish his plugin to some plugin index?

**Comment by akirak** [comment]
@Septias Indeed, you can define your own Emacs Lisp package from a given source using `pkgs.emacs.pkgs.melpaBuild` function. Then you can add the package to the scope by calling `pkgs.emacs.pkgs.overrideScope` function. 

There is also [emacs-twist](https://github.com/emacs-twist/twist.nix) project, which could be a better fit for package development, but it is still at alpha stage, so I wouldn't recommend it. I am the author of the project.

**Comment by Septias** [comment]
I'm new to emacs, the provided configuration uses `quelpa` can I still build stuff with `melpa`?

**Comment by m-fleury** [comment]
@Septias I use quelpa because it is able to clone git repos from github. `melpa` would be better but the package (at least at the beginning) required a specific isabelle version to work correctly.

**Comment by adisbladis** [comment]
@akirak has provided the correct guidance. Closing as this is not an overlay issue.

**Comment by Septias** [comment]
If I understand correctly, I can use nix to add the packages (isar-mode, isar-goal-mode, lsp-isar) and then modify my emacs.el to just require them from melpa and keep the configuring steps like `:init (add-hook)`, `:config` etc. ?

**Comment by Septias** [comment]
With this approach, I still want to use  `pkgs.emacsWithPackagesFromUsePackage` to specify my configuration file. But to correctly load the config file, `emacsWithPackagesFromUsePackage` needs to know of the new packages. I don't see how to do that here. `pkgs.emacs.pkgs.overrideScope` doesn't allow me to specify a config I guess.

**Comment by Septias** [comment]
```

{
  pkgs,
  ...
}: 
    pkgs.emacsWithPackagesFromUsePackage {
      package = pkgs.emacsGit;  # replace with pkgs.emacsPgtk, or another version if desired.
      config = ./emacs.el;
      # config = path/to/your/config.org; # Org-Babel configs also supported

      # Optionally provide extra packages not in the configuration file.
      # extraEmacsPackages = epkgs: with epkgs; [
      #   lsp-mode
      #   session-async
        
      # ];

      # Optionally override derivations.
       override = epkgs: epkgs // {
        isar-mode = pkgs.emacs.pkgs.melpaBuild {
          pname = "isar-mode";
          version = "git-fresh";
          src = pkgs.fetchFromGitHub {
            owner = "m-fleury";
            repo = "isar-mode";
            rev = "354b881";
            hash = "";
          };
          files = "*.el";
        };
      };
}
```
This gives me `function 'anonymous lambda' called without required argument 'recipe'` even though recipe is an optional argument in melpaBuild (https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/build-support/melpa.nix).

**Comment by akirak** [comment]
@Septias `override` takes two arguments:

```nix
  override = final: prev:
     {
      isar-mode = prev.melpaBuild {
        pname = "isar-mode";
        version = "git-fresh";
        src = pkgs.fetchFromGitHub {
          owner = "m-fleury";
          repo = "isar-mode";
          rev = "354b881";
          hash = "";
        };
        # files = "*.el";
      };
    };
```

You can omit `files` if the files reside in the top-level directory (see [the MELPA recipe format](https://github.com/melpa/melpa?tab=readme-ov-file#recipe-format) for a complete definition).

**Comment by Septias** [comment]
I somehow still get function `'anonymous lambda' called without required argument 'recipe'` even with your file

**Comment by Septias** [comment]
Ah, because I'm actually using `https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/build-support/emacs/melpa.nix`

**Comment by Septias** [comment]
I had to use my unstable overlay to get the newest version of melpaBuild because 24-05 only provides `https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/build-support/emacs/melpa.nix` which requires `recipe`.

**Comment by Septias** [comment]
I noticed that some variables for example `(setq lsp-isar-path-to-isabelle "~/Documents/isabelle/isabelle-emacs")` from the `init.el` are not properly set (They still have the default value when inspected in emacs). Is that because only packages are extracted for installation? Also, when is init.el evaluated? When I added `aedtruibade` at the end, hom-manager rebuild still succeded.

**Comment by m-fleury** [comment]
`init.el` is one of the possible names of the emacs configuration files. You have to set the correct path to point to where you installed Isabelle-emacs.

**Comment by Septias** [comment]
The problem is that the variable is not set at all.

**Comment by m-fleury** [comment]
According to https://emacs.stackexchange.com/questions/51559/difference-between-emacs-and-init-el-and-the-point-of-not-keeping-multiple-in, init.el is the last file to be read. Do you have another config file?

**Comment by Septias** [comment]
I have not configured any init.el file because I added it to the emacs derivation, thinking it would perform all required steps. I'm not quite sure though if that really happens.
