### ISSUE TITLE
emacs-emacsql-sqlite does not build

### ISSUE THREAD

**Issue by jyp** [nix-community/emacs-overlay#421]
I am getting the following error with revision 6bbe8973c0a99ebb54175310f20a0d255f688f90:

```
nix log /nix/store/kfy455kkpszfs1n31f2zqsxid2fwnzlw-emacs-emacsql-sqlite-20240825.1837.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/kfy455kkpszfs1n31f2zqsxid2fwnzlw-emacs-emacsql-sqlite-20240825.1837.drv^*'
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/vf0qdv8kh5acxa0h0ysmyyyhw9b6iwgx-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
/nix/store/bc0as359y5y067dfp7afrq1f011m9ny3-stdenv-linux/setup: line 114: cd: source/sqlite: No such file or directory
```

It is very unclear how to proceed from here, any help appreciated.

**Comment by adisbladis** [comment]
This is not an overlay issue. This looks like a broken override, and those live in nixpkgs.

**Comment by jyp** [comment]
@adisbladis Thanks for the quick reply. However, please consider the following:
- there is no mention of sqlite in my config (so I don't think that there is an override of it at all)
- the system builds well without the emacs overlay

With this in mind I am inclined to believe that there is at least a bad interaction between standard nixpkgs and the emacs overlay. Regardless, perhaps you could give me a clue as how to proceed to address the issue?

**Comment by jyp** [comment]
In case someone finds this: the problem seem to have been caused by my explicit requiring a package from melpa stable.

**Comment by pmiddend** [comment]
I'm experiencing the same issue and do not require anything from melpa stable.
