### ISSUE TITLE
XWidgets on macos

### ISSUE THREAD

**Issue by puhsu** [nix-community/emacs-overlay#422]
Emacs supports and builds with xwigets on mac os since 28 (see [NEWS](https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS?h=emacs-28#n2625)). How do I build emacs with Xwidgets on mac with nix? I see the assert in the nixpkgs emacs build file [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/make-emacs.nix#L133) and emacs currently does not build with xwidgets on macos with nix. What's the best way of fixing this? Should I change make-emacs.nix in nixpkgs to remove the assert, or can I override this within the emacs-overlay?

**Comment by adisbladis** [comment]
> Should I change make-emacs.nix in nixpkgs to remove the assert, or can I override this within the emacs-overlay?

Probably that's the best solution. In any case, this is not an overlay issue.
