### ISSUE TITLE
Issues with home directory

### ISSUE THREAD

**Issue by mgttlinger** [nix-community/emacs-overlay#430]
I recently switched to the use-package functionality here, however, it seems some packages like e.g. AucTeX  fail to compile properly in this way as they try to change the working directory to the user home which is set to the non-existing folder `/homeless-shelter` during the sandboxed nix build.

Is this an issue with this overlay or usage error on my side?

**Comment by jian-lin** [comment]
> Is this an issue with this overlay or usage error on my side?

This is a Nixpkgs issue and has been [fixed](https://github.com/NixOS/nixpkgs/pull/343925/commits/fc9502ff295c22cc8114ecc6b550c3b0db41c267#diff-33ecf7a2394b9f266c2f2f78ec3b69ae430f326d0aa8ab82a4707cc7a6008e17R71).
