### ISSUE TITLE
Xwidget support

### ISSUE THREAD

**Issue by sjLambda** [nix-community/emacs-overlay#443]
File mode specification error: (error Eager macro-expansion failure: (error "Your Emacs was not built with Xwidget support"))

Just started getting this error with recent compile and install of emacs-pgtk. Is there a way I can add this option to my nix file before compiling but still use the overlay? Thanks for any other suggestions.

**Comment by jian-lin** [comment]
Xwidget needs `webkitgtk`.  However, `webkitgtk >= 2.41.92` makes Emacs crash.  See this upstream Emacs [bug] for more information.

To actually use Xwidget, you need to provide Emacs an old enough `webkitgtk`.

[bug]: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=66068#47
