### ISSUE TITLE
compile mode Bash not found

### ISSUE THREAD

**Issue by EduardoSilvaDiniz** [nix-community/emacs-overlay#445]
i'm having trouble using compile mode, i'm getting the error
```
“/nix/store/pd228xy0lni9xbghrpxig5v0cyh2bwps-emacs-git-20240915.0/bin/emacs: /bin/bash: No such file or directory”.
```
I tried to fix it by defining another shell but the problems persist.
```emacs-lisp
(setq explicit-shell-file-name “/bin/zsh”)
(setq shell-file-name “/bin/zsh”)
```
but compile mode still can't find the shell, even if I switch to zsh.
project mode doesn't work either.
```
“/nix/store/pd228xy0lni9xbghrpxig5v0cyh2bwps-emacs-git-20240915.0/bin/emacs: /bin/zsh: No such file or directory”
```
my emacs home manager configuration
```nix
{pkgs, ...}: {
  programs.emacs = {
    enable = true;
    package = pkgs.emacs-git;
    extraPackages = epkgs:
      with epkgs; [
        treesit-grammars.with-all-grammars
        vterm
        mu4e
      ];
  };
  home.packages = import ./lsps.nix {inherit pkgs;};
}
```
![Captura de tela de 2024-10-24 11-19-50](https://github.com/user-attachments/assets/94fac8d0-163b-4141-b8de-832663684b4e)

**Comment by adisbladis** [comment]
If you're on NixOS `/bin/bash` doesn't exist by design. That would be `/run/current-system/sw/bin/bash`.
