### ISSUE TITLE
How to install a custom tree-sitter grammar?

### ISSUE THREAD

**Issue by arthsmn** [nix-community/emacs-overlay#446]
I saw https://github.com/nix-community/emacs-overlay/issues/341 and wondered how could I install a custom one. I currently would like to use https://github.com/dataphract/kdl-ts-mode and it depends on https://github.com/dataphract/tree-sitter-kdl, but I can't figure out how to make the grammar available.

**Comment by adisbladis** [comment]
Not an overlay issue. 

For packaging grammars look in nixpkgs.
