### ISSUE TITLE
Missing dependencies for `skewer-mode`

### ISSUE THREAD

**Issue by YTG1234** [nix-community/emacs-overlay#453]
The package requires `js2-mode` and `simple-httpd`, but they aren't provided, so the build fails.

Adding them using an override solves the issue, i.e.
```nix
emacsPackages.skewer-mode.overrideAttrs (prev: {
  buildInputs = prev.buildInputs ++ [ emacsPackages.simple-httpd emacsPackages.js2-mode ];
  # Repeat for propagatedBuildInputs and propagatedUserEnvPkgs
})
```

On revision `6c65dad`.

**Comment by marienz** [comment]
Commit 91394111f9fad62bd7c909dcdb149d4cf4594487 dropped dependencies from several packages (including skewer-mode). Other suspicious ones I've noticed are `ddskk` dropping its dependency on `ccc`, `emacs-eclim` dropping all its dependencies (including `dash`).

An interesting outlier is clojure-snippets, which *gained* a dependency on `cl-lib`.

I suspect MELPA no longer picks up dependencies defined in `define-package` in `-pkg.el` files (like https://github.com/mpenet/clojure-snippets/blob/66d23f0ffedf2cc2be0387c3504b5f89d7300cfa/clojure-snippets-pkg.el) and is only picking them up from `Package-Requires` headers (like https://github.com/mpenet/clojure-snippets/blob/66d23f0ffedf2cc2be0387c3504b5f89d7300cfa/clojure-snippets.el#L8).

I'm not sure which MELPA change might have caused that, but it might be https://github.com/melpa/melpa/commit/064927ca37912aba45f449635b42cd38c0e9d8cd (haven't looked closely enough to be sure yet).

**Comment by marienz** [comment]
Yeah, I *think* we want to hit [`package-build--extract-from-package`](https://github.com/melpa/melpa/blob/9b90415a9d145aee22f9b1268a5b432369c7f7ec/package-build/package-build.el#L1258-L1272) to get those dependencies extracted, which means `package-build--build-multi-file-package`, while I think that commit switched to `package-build--build-package`, which calls `package-build--extract-from-library` instead (to extract that information from a `Package-Requires` header).

Not entirely sure this is actually broken on the MELPA side, but no dependencies listed on https://melpa.org/#/skewer-mode either makes me suspect it might be...

**Comment by marienz** [comment]
Ah, the second half of the commit message of https://github.com/melpa/package-build/commit/760cf53114a6f27e86bc87b44726ced34bcda0ea looks relevant:

> - Melpa stopped using `package-build--build-multi-file-package'
>   recently, in favor of `package-build--build-package'.  While the
>   former also extracted metadata from "NAME-pkg.el", the latter only
>   uses "NAME.el".  This makes sense because only very few packages
>   provide a "NAME-pkg.el" file, when it does exist it often contains
>   outdated information, and [Non]GNU ELPA also ignores these files.

So it sounds like this was a deliberate change.

**Comment by marienz** [comment]
Hm, affects a bunch of packages, with smartparens being possibly the highest-profile one (sent https://github.com/Fuco1/smartparens/pull/1221 to fix that one upstream).

(Also, when working around this using an override, instead of adding to all three of buildInputs, propagatedBuildInputs and propagatedUserEnvPkgs, adding to just packageRequires should have the same effect.)

**Comment by YTG1234** [comment]
> (Also, when working around this using an override, instead of adding to all three of buildInputs, propagatedBuildInputs and propagatedUserEnvPkgs, adding to just packageRequires should have the same effect.)

You're right, of course… I hadn't noticed that `packageRequires` actually gets included in the final `mkDerivation` call, I thought it was just being used along the way.

**Comment by marienz** [comment]
Now also reported as https://github.com/melpa/melpa/issues/9285

**Comment by marienz** [comment]
Melpa rolled back their change (so once emacs-overlay updates from melpa again that should fix it here, too).

**Comment by adisbladis** [comment]
Fixed in update commit https://github.com/nix-community/emacs-overlay/commit/f44e986695256fa0fde8ef7198c5633e8adfba5f
