### ISSUE TITLE
emacsWithPackagesFromUsePackage no longer works with configuration files in org-mode format

### ISSUE THREAD

**Issue by alexvorobiev** [nix-community/emacs-overlay#46]
My main configuration file is in org-mode format loaded by `init.el`. After the recent update the overlay is no longer able to obtain the `use-package` declaration from it. Instead it fails right away:

`
error: Unrecognized token on line 1: #+TITLE: Emacs configuration
`

**Comment by alexvorobiev** [comment]
I didn't notice https://github.com/nix-community/emacs-overlay/issues/44.

**Comment by adisbladis** [comment]
See my comment here: https://github.com/nix-community/emacs-overlay/issues/44#issuecomment-667354701.
