### ISSUE TITLE
`emacsWithPackagesFromUsePackage` fails on some characters 

### ISSUE THREAD

**Issue by matthew-piziak** [nix-community/emacs-overlay#55]
My configuration contains characters like `ι` and `‥`. This fails `emacsWithPackagesFromUsePackage` builds.

**Comment by talyz** [comment]
This is, to my knowledge, an unfortunate limitation of Nix - no unicode support at all. [fromElisp](https://github.com/talyz/fromElisp), which is used to parse the elisp, is written in Nix and therefore limited in this sense. I ran into this issue myself and couldn't find any way to work around it other than getting rid of the offending lines from my config. :/

**Comment by matthew-piziak** [comment]
Thank you @talyz!
