### ISSUE TITLE
Support for pure gtk emacs.

### ISSUE THREAD

**Issue by ishan9299** [nix-community/emacs-overlay#57]
There is work going on to make emacs a pure gtk3 application so that it can run in wayland without Xwayland. There are 2 mirrors which we can use :-

- https://github.com/fejfighter/emacs (it seems they are planning to merge this one upstream)
- https://github.com/masm11/emacs

Would it be possible to make a package for it like emacsPureGtk ?

**Comment by adisbladis** [comment]
I'm reluctant to add new derivations for non-official efforts, I'd be more inclined to do so if there was an official upstream branch we could track.

**Comment by ishan9299** [comment]
I don't think there is an official branch for emacs (for this particular issue). Most if the work is being done by both fejfighter and masm11 for the pure gtk version of emacs it would also become easier to test eamcs in wayland as experience with Xwayland and emacs is not really pleasant.

**Comment by adisbladis** [comment]
I'm gonna say no on this until there is an at least semi-official upstream we can choose.
