### ISSUE TITLE
builtin packages in use-package

### ISSUE THREAD

**Issue by peel** [nix-community/emacs-overlay#6]
use-package allows for bundling together package-related configuration, which allows for cleaner, more effective init.
Example:
```elisp
(use-package dired
  :ensure nil
  :config
  (setq dired-dwim-target t
        dired-recursive-deletes t
        dired-use-ls-dired nil
        delete-by-moving-to-trash t))
```
Currently it is not possible to use the kind of approach with the overlay.
`elisp.nix` searches matched packages in the package set, but as they are builtin they are not in the set. I made a quick [workaround](https://github.com/peel/emacs-overlay) but haven't gotten around to make it clean and PR-ready.

Thank you for the great work!

**Comment by adisbladis** [comment]
I've also noticed this problem but wasn't sure of what solution to go for.

I was considering simply making failed `use-package` lookups return `null` as that would require zero maintenance going forward.
 What do you think of this?

**Comment by peel** [comment]
Definitely makes sense and that's the least maintenance-burden :+1:

Though having a `xxxx attribute missing` was helpful when diagnosing the problem.
With the `null` yielded for both truly missing and builtin packages we'd lose the kind of safety net.

**Comment by marzipankaiser** [comment]
For this and #8, the clean solution for me would seem to be parsing `use-package`'s `:ensure` arguments, [this](https://github.com/jwiegley/use-package#usage-with-other-package-managers) could then be used to prevent `package.el` from running.
That way, existing configs should kind of "just work" and special packages (e.g. where the package name is different for use-package and nixpkgs) can be handled in a readable way.
This would, however, mean writing a much more complicated parser.
I currently do not have the time to implement this, and I'm happy with other solutions, but I saw this in the `use-package` docs and thought I'd share the idea.

**Comment by alexvorobiev** [comment]
Would creating an alias for `use-package` so that the parser in the overlay wouldn't find it, e.g.
```
(defalias 'use-local-package 'use-package)
```
be another workaround? Then use this alias for local packages.

**Comment by adisbladis** [comment]
@alexvorobiev That would work but feels hacky. I want the experience of adopting Nix for emacs configuration management to be as smooth as possible
You should be able to take your configuration unmodified and pass it to `fromEmacsUsePackage`.

**Comment by adisbladis** [comment]
Closed by merging https://github.com/nix-community/emacs-overlay/pull/43.

**Comment by Septias** [comment]
Hi, I'm completely new to emacs so sorry if this is a noob question. I'm trying to configure emacs for isabelle and I took [this](https://github.com/m-fleury/isabelle-emacs/blob/Isabelle2024-vsce/src/Tools/emacs-lsp/spacemacs_layers/isabelle/README.org#install-as-a-non-developer) official install script. I still get `error: Emacs package isar-mode, declared wanted with use-package, not found.`. I want it installed and there is this weird `:ensure t` which I don't understand the meaning of. Can someone help?

emacs.el for reference:
```
;; initialisation of package (if needed)
(package-initialize)

(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)

(unless (package-installed-p 'use-package)
  (message "installing package use-package")
  (package-refresh-contents)
  (package-install 'use-package)

  (unless (package-installed-p 'use-package)
    (error "failed to install use-package"))
  )

;; install quelpa
(use-package quelpa
  :ensure t)

(require 'quelpa)

(quelpa
 '(quelpa-use-package
   :fetcher git
   :url "https://github.com/quelpa/quelpa-use-package.git"))

(require 'quelpa-use-package)

;; install dependencies
(use-package lsp-mode
  :ensure t)
(use-package session-async
  :ensure t)


;; the various required packages
(use-package isar-mode
  :ensure t
  :mode "\\.thy\\'"
  :quelpa (isar-mode :fetcher github
		     :repo "m-fleury/isar-mode"
		     :files ("*.el")
		     :upgrade t)
  )

(use-package isar-goal-mode
  :ensure t
  :quelpa (isar-goal-mode :fetcher github
			  :repo "m-fleury/simp-isar-mode"
		     :files ("*.el")
		     :upgrade t))

(use-package lsp-isar
	     :ensure t
	     :quelpa ((lsp-isar :fetcher github
				:repo "m-fleury/isabelle-emacs"
				:branch "Isabelle2023-vsce"
				:files ("src/Tools/emacs-lsp/lsp-isar/*.el"))
				:upgrade t)
  :after lsp-mode
  :commands lsp-isar-define-client-and-start
  :defer t
  :init
  (add-hook 'isar-mode-hook #'lsp-isar-define-client-and-start)
  (add-hook 'lsp-isar-init-hook 'lsp-isar-open-output-and-progress-right-spacemacs)
  :config

  ;; CHANGE HERE: path to isabelle-emacs repo
  (setq lsp-isar-path-to-isabelle "~/Documents/isabelle/isabelle-emacs")

  )
```
