### ISSUE TITLE
seq from elpa seem to conflict (infinite recursion) with seq included in emacsUnstable

### ISSUE THREAD

**Issue by alexvorobiev** [nix-community/emacs-overlay#60]
I have switched to emacsUnstable and immediately started having issues with seq package from elpa which is now also included in emacs 27:

```
Debugger entered--Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
  seq-subseq((24372 49279 730919 565000) 0 2)
  cl-subseq((24372 49279 730919 565000) 0 2)
...
  seq-subseq((24372 49279 730919 565000) 0 2)
  cl-subseq((24372 49279 730919 565000) 0 2)
  org-file-newer-than-p("~/.emacs.d/config.el" (24372 49194 929518 551000))
  org-babel-load-file("~/.emacs.d/config.org")
  eval-buffer(#<buffer  *load*> nil "/home/alex/.emacs.d/init.el" nil t)  ; Reading at buffer position 3253
  load-with-code-conversion("/home/alex/.emacs.d/init.el" "/home/alex/.emacs.d/init.el" t t)
  load("/home/alex/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x711b25>) #f(compiled-function () #<bytecode 0x711b39>) t)
  command-line()
  normal-top-level()
```

I found similar issues in other projects (https://github.com/hlissner/doom-emacs/issues/1990#issuecomment-549140718). Evaluating the definition from https://github.com/hlissner/doom-emacs/issues/1990#issuecomment-549215813 seems to fix the issue. Is there a way to remove the dependency on elpa seq in emacsUnstable?

**Comment by terlar** [comment]
How do you install packages? This should already be fixed:
https://github.com/NixOS/nixpkgs/pull/74936

**Comment by gamb** [comment]
I ran into the same issue with `alwaysEnsure = true`:
```nix
myEmacs = pkgs.emacsWithPackagesFromUsePackage {
  config = builtins.readFile ./init.el;
  package = pkgs.emacsUnstable;
  alwaysEnsure = true;
};
```

**Comment by gamb** [comment]
Building with `nix-env -i -f emacs.nix`, where `init.el` has contents:
```
(require 'package)

(use-package flycheck)
```
Startup (`--debug-init`) results in: https://gist.github.com/gamb/9061985be9d0d839df4bbe231a359d91

**Comment by gamb** [comment]
I guess this version isn't matching the conditional patch on `seq`?
```
nix-repl> emacs26.version
"26.3"

nix-repl> emacsUnstable   
«derivation /nix/store/5isxq9id5qd5xw9npg9wvdrh2bk32r9c-emacs-unstable-emacs-27.1.drv»

nix-repl> emacsUnstable.version
"emacs-27.1"
```
cf. if it were `"27.1"` would it match `seq = if lib.versionAtLeast self.emacs.version "27`

**Comment by adisbladis** [comment]
This seems to not be an issue anymore.
