### ISSUE TITLE
Slow Unicode rendering on `emacsGcc`

### ISSUE THREAD

**Issue by matthew-piziak** [nix-community/emacs-overlay#62]
To reproduce:
1. install `emacsGcc`. 
2. run `emacs -q`
3. invoke `M-x view-hello-file`.

Notice that this freezes Emacs. This is due to the Unicode characters displayed on that page.

The same actions on `emacsUnstable` will result in the Hello page being displayed normally.

**Comment by adisbladis** [comment]
This is probably better reported upstream.

**Comment by adisbladis** [comment]
Feel free to reopen if this is caused by a packaging bug.

**Comment by matthew-piziak** [comment]
I haven't reported it upstream, lest someone think I've linked the cookie. I've just reverted to `emacsUnstable`, as the `emacsGcc` expression is unsuitable for any uses encountering emoji or unusual Unicode blocks. I do not know whether or not this is caused by a packaging but or not.

**Comment by matthew-piziak** [comment]
This might be worth telling users. I suppose they might find this closed bug if they look for it.

**Comment by matthew-piziak** [comment]
I made a mistake. I ran `pkgs.emacsUnstable` from this overlay with no other customization, and it appears that the regression is between `pkgs.emacs` and `pkgs.emacsUnstable`, not between `pkgs.emacsUnstable` and `pkgs.emacsGcc`.

I have confirmed that non-Nix builds of emacsgcc do not have this issue, which means it's something in the default configuration.

**Comment by matthew-piziak** [comment]
Alas, I do not have re-open privileges.
