### ISSUE TITLE
emacsGcc build fails : Symobl's value as variable is void auto-save-list-file-prefix

### ISSUE THREAD

**Issue by mjlbach** [nix-community/emacs-overlay#64]
As of https://github.com/nix-community/emacs-overlay/commit/1f6b53563d4f015d03bb24bd654d01b4942c06b4, I (and [hydra])(https://hydra.nix-community.org/build/1944862) get the following error on building emacsGcc from commit https://github.com/emacs-mirror/emacs/commit/8a931a97b8dd19a38d6f719f810280a07ba76438

```
chmod 755 "/nix/store/bx0wjfyvjlx0zc99xlzwa0q76fgmy1rr-emacs-gcc-20200819.0/bin/`echo emacs-28.0.50 | sed 's,x,x,'`"
rm -f "/nix/store/bx0wjfyvjlx0zc99xlzwa0q76fgmy1rr-emacs-gcc-20200819.0/bin/`echo emacs | sed 's,x,x,'`"
cd "/nix/store/bx0wjfyvjlx0zc99xlzwa0q76fgmy1rr-emacs-gcc-20200819.0/bin" && ln -s "`echo emacs-28.0.50 | sed 's,x,x,'`" "`echo emacs | sed 's,x,x,'`"
make -C lib-src maybe-blessmail
make[1]: Entering directory '/build/source/lib-src'
make[1]: Nothing to be done for 'maybe-blessmail'.
make[1]: Leaving directory '/build/source/lib-src'
find eln-cache -type f -exec /nix/store/gd3nl6hcc8mzq8fmxdvl6czh3l0n4la5-coreutils-8.31/bin/install -c -m 644 -D "{}" ""/nix/store/bx0wjfyvjlx0zc99xlzwa0q76fgmy1rr-emacs-gcc-20200819.0/libexec/emacs/28.0.50/x86_64-pc-linux-gnu/"{}" \;
Symbol's value as variable is void: auto-save-list-file-prefix
builder for '/nix/store/sg8b2y9zz2n9fj1gk2mzh71k18izcdyh-emacs-gcc-20200819.0.drv' failed with exit code 255
cannot build derivation '/nix/store/w8sp6xr9qkkf9kwms77vz9v76wgrw3wl-emacsGccWrapped.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/304qc313r1icpk1xp6908q8bidh4di60-emacsGccWrapped-with-packages-.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/v3q747lpsbigmydg4dic5hd5nymirc9g-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/lckdw9lr4g3p15acd9540fnc0yn7s0mv-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/lckdw9lr4g3p15acd9540fnc0yn7s0mv-home-manager-generation.drv' failed
```

**Comment by mjlbach** [comment]
Could this be due to the movement of the eln-build-cache in the latest native-comp update? I can investigate tomorrow

**Comment by mogorman** [comment]
can confirm have same problem

**Comment by mjlbach** [comment]
I sent the bug report to the mailing list

**Comment by mogorman** [comment]
I was able to build this morning

**Comment by mjlbach** [comment]
From the mailing list:

'''

Hi thanks for the report, I've reverted 8a931a97b8.

What's going on is that hashing the eln based on the last mod time
simply breaks make install as the last modification time is not
preserved precisely.

I think we could work out the makefile to try to preserve that but I
believe is worth trying to hash using the .el file content and see if it
has a performance impact or not. If viable I believe would be a more
robust solution.

I propose we hash like filename-path_hash-content_hash.eln so we can
clean-up the eln-cache folders when recompiling or when we want.

Could you please check in the meanwhile that is back working for you?

Thanks!

Andrea
'''
