### ISSUE TITLE
Recommended way to install non-(m)elpa packages?

### ISSUE THREAD

**Issue by alexvorobiev** [nix-community/emacs-overlay#66]
I want to install a package from its git repository (e.g. https://github.com/dustinlacewell/eyeliner). Prior to using the overlay I did it with straight.el. What is the recommended way to install it with the emacs-overlay?

**Comment by akirak** [comment]
You can use functions from `build-support` directory in `nixpkgs`, e.g. `melpaBuild` and `trivialBuild`. There are examples in `emacs-modes` directory: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs-modes/melpa-packages.nix. You won't need `emacs-overlay` to define your own package derivations.

**Comment by alexvorobiev** [comment]
I was able to add the "inline" declaration of the additional package:
```
    extraEmacsPackages = epkgs: [
        epkgs.org-plus-contrib

        (epkgs.melpaBuild {
             pname = "...";
          ...
        })
    ];
```
But when I tried to put it in a separate file and use `callPackage`, somehow the arguments (`epkgs.melpaBuild`, `pkgs.writeText`, etc.) weren't passed there.

**Comment by akirak** [comment]
Sorry, I don't get the context. How did you call `callPackage`? Could you show me the concrete source code?

**Comment by akirak** [comment]
Also note, [this](https://discourse.nixos.org/) may be a better place to ask questions, since your question has nothing to do with `emacs-overlay`.

**Comment by adisbladis** [comment]
Closing this as it has nothing to do with this overlay.
