### ISSUE TITLE
could you add some extra documentation on the usage of the emacs-overlay ?

### ISSUE THREAD

**Issue by zeta-00** [nix-community/emacs-overlay#68]
hello there,
i'm having trouble adding rev and sha to the emacs-layer usage section: https://github.com/nix-community/emacs-overlay#usage-of-the-overlay, so could you add some extra documentation on how to do this, i don't think that you can add rev or sha as an argument to fetchTarbal? anyways here's the same question that i posted on reddit if you want to take a look: https://www.reddit.com/r/NixOS/comments/ii1e3y/how_to_correctly_update_emacs_packages_in_nixos/

thanks in advance for the help !

**Comment by terlar** [comment]
`fetchTarball` does indeed take a sha256:
https://nixos.org/manual/nix/stable/#builtin-fetchTarball

Regarding the revision you can just update the URL with the git commit sha instead of using the branch name “master”

**Comment by adisbladis** [comment]
With the addition of the Quickstart section I think we can close this.
