### ISSUE TITLE
emacsGcc compilation errors

### ISSUE THREAD

**Issue by acowley** [nix-community/emacs-overlay#69]
All package compilation output in `*Async-native-compile-log*` is resulting in,

```
x86_64-unknown-linux-gnu-gcc-9.3.0: fatal error: cannot execute ‘as’: execvp: No such file or directory
compilation terminated.
```

**Comment by spacekitteh** [comment]
You need to add `binutils` in the `extraPackages`, as it was taken out by default for some reason or other in the latest unstable channel.

**Comment by acowley** [comment]
@spacekitteh Thank you for the hint! Which `extraPackages` do you mean? I’m having trouble finding that attribute. Is there a PR fixing this problem already, or, if not, if you can link the commit that introduced the problem I can open a PR to fix it.

**Comment by spacekitteh** [comment]
Whoops, I forgot `extraPackages` was a `home-manager` thing. I think you'll need to override the `emacsGcc` derivation.
