### ISSUE TITLE
dlopen issue on macOS

### ISSUE THREAD

**Issue by adelbertc** [nix-community/emacs-overlay#71]
Trying to build this with an overlay setup that looks like:

```nix
# emacs-native.nix
import (builtins.fetchTarball {
  url = https://github.com/nix-community/emacs-overlay/archive/aa69bf3bdc4e63c3a1a3d0f1a8273a9755d8ae4c.tar.gz;
})

# emacs.nix
...
    emacsPackagesNg =
      let
        pkgs = import (fetchGit {
          url = "https://github.com/NixOS/nixpkgs.git";
          # Merge commit of https://github.com/NixOS/nixpkgs/pull/94637
          rev = "6fc3562432357cdbcbb30804b47feacfac452acb";
        }) { };
      in
        pkgs.emacsPackagesNgGen self.emacsGcc;
...
```

I get most of the way through a build but eventually hit:

```nix
emacs: dlopen(../native-lisp/28.0.50-x86_64-apple-darwin18.7.0-d06f2377a88b929de7de130ac33e3632/lisp-mode-0189ba85598c041b7504f0a916c04219-1738806322de892570d69dfc55b437c2.eln, 1): image not found
builder for '/nix/store/6xgzwbg9m613ihvs3p97sqlwr6xy9n3x-emacs-company-20200920.2215.drv' failed with exit code 1
cannot build derivation '/nix/store/9klf4mwnshdqqa2yp367rgd3znn2kxkw-personal-emacs.drv': 1 dependencies couldn't be built
error: build of '/nix/store/9klf4mwnshdqqa2yp367rgd3znn2kxkw-personal-emacs.drv' failed
```

Any ideas?

**Comment by dhess** [comment]
I'm able to build emacsGcc on macOS, but I get a similar error when trying to launch it. Trying to open `~/Applications/Emacs.app` results in:

```
LSOpenURLsWithRole() failed with error -10810 for the file /Users/dhess/Applications/Emacs.app.
```

Playing around and chasing down symlinks, if I then try to run the wrapped binary, I get this:

```
 /nix/store/bjimk5b4j5vxhc4dg7ag9x7sa7aqagqi-emacs-gcc-20200926.0/Applications/Emacs.app/Contents/MacOS/Emacs 
emacs: dlopen(/nix/store/bjimk5b4j5vxhc4dg7ag9x7sa7aqagqi-emacs-gcc-20200926.0/Applications/Emacs.app/Contents/MacOS/../native-lisp/28.0.50-x86_64-apple-darwin19.6.0-aa25a7c9bc2108f49cb1928d907c6ef3/lisp-mode-0189ba85598c041b7504f0a916c04219-1738806322de892570d69dfc55b437c2.eln, 1): image not found
```

**Comment by nuance** [comment]
I've found that if I cd into the same directory as the emacs binary (eg `/nix/store/bjimk5b4j5vxhc4dg7ag9x7sa7aqagqi-emacs-gcc-20200926.0/Applications/Emacs.app/Contents/MacOS/` in @dhess's example) and run emacs as `./emacs` it seems to work.

I'm not sure what the fix would be, but hopefully that's useful?

**Comment by Atemu** [comment]
Running Emacs from Contents/MacOS/ didn't work for me, I needed to run it from bin/emacs.

**Comment by yuanl** [comment]
Found a solution in [this commit](https://github.com/twlz0ne/nix-gccemacs-sierra/commit/e83f1315256c9dc7590cbd067bc5bbbb7875bebd).
You need to create a symlink in Emacs.app/
```sh
ln -snf $out/lib/emacs/28.0.50/native-lisp $out/Applications/Emacs.app/Contents/native-lisp
```
Sorry, I couldn't post a PR, as I don't know how to do it in Nix yet.

**Comment by adisbladis** [comment]
I believe this can be closed since https://github.com/NixOS/nixpkgs/pull/103933 is merged, if not reopen please :)
