### ISSUE TITLE
Emacs C source-directory?

### ISSUE THREAD

**Issue by xcthulhu** [nix-community/emacs-overlay#72]
Hi!

I was wondering if there is a way I could do `(setq source-directory <...>)` using this overlay so that `elisp-slime-nav` could jump to symbol definitions in the C source code.

**Comment by leungbk** [comment]
There's an issue already at nixpkgs: https://github.com/NixOS/nixpkgs/issues/98615

**Comment by xcthulhu** [comment]
I'll close this then in favor of that ticket.

**Comment by xcthulhu** [comment]
According to NixOS/nixpkgs#98615 this is fixed upstream, but it's still not functioning properly for the overlay

**Comment by adisbladis** [comment]
This works just fine.

Verified by building `emacsUnstable` and using jump to definition (`M-.`).
