### ISSUE TITLE
[gccemacs] Should fast bootstrap continue to be the default?

### ISSUE THREAD

**Issue by leungbk** [nix-community/emacs-overlay#73]
[A new default was added in the past couple of weeks](https://akrl.sdf.org/gccemacs.html#orgac3b809), making [fast bootstrap](https://akrl.sdf.org/gccemacs.html#orgf815332) the default build target. I haven't yet tried `gccemacs`, so I'm not sure how this default and `make NATIVE_FULL_AOT=1` compare on Nix. From reading the updates, it seems like with the default setting, some non-essential parts of Emacs are native-compiled at runtime (which doesn't appear to make sense on Nix since the Nix store is read-only), whereas with `make NATIVE_FULL_AOT=1`, all the Elisp files in base Emacs are native-compiled before the user can begin using it. Do I have this right, and if so, should the overlay set `NATIVE_FULL_AOT`?

**Comment by collares** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/104010: https://github.com/NixOS/nixpkgs/blame/256bfd2f972a6fbaeb33b8acf9821d021f947597/pkgs/applications/editors/emacs/generic.nix#L46
