### ISSUE TITLE
Nixos + Emacs + Fontconfig 2.13 = hangs

### ISSUE THREAD

**Issue by spacekitteh** [nix-community/emacs-overlay#75]
So it seems that Fontconfig takes AGES (like, 2-3 minutes) to return fonts for a lot of characters now, but only in emacs (27, 28) on NixOS (works fine on nix on ubuntu). It makes GUI emacs unusable for me. To reproduce:

1. `emacs -Q`
2. `M-x describe-fontset RET RET`

--- Original for posterity ---
This occurs on both `master` and `native-comp` branches. I'm running NixOS on `unstable`.

An example is `spaceline-all-the-icons`

**Comment by tadfisher** [comment]
Is it fixed after you delete `~/.cache/fontconfig`? I have tons of issues when fonts are updated by `home-manager`, but clearing the font cache fixes it.

**Comment by spacekitteh** [comment]
Nope, it's due to fontconfig's search behaviour.

**Comment by juaningan** [comment]
I've noticed this error when Emacs try to draw any emoji or weird unicode chars.

**Comment by spacekitteh** [comment]
So, this was due to fontconfig's slow searching of the adobe blank font. Remove that font and you'll be good :)
