### ISSUE TITLE
how to install specific version

### ISSUE THREAD

**Issue by PlumpMath** [nix-community/emacs-overlay#76]
I'd like to specific version emacs this overlay. (Pin?)
Thanks.

**Comment by etu** [comment]
It depends on how you get the overlay onto your system. If you follow this https://github.com/nix-community/emacs-overlay#latest-master-each-rebuild

Then you can replace the word `master` in there (which is the branch name) with a commit id (for exapmle `3c649677294bdedb776ec69b14719b7171666a8a` which is the latest commit on master as of writing).

:slightly_smiling_face:

**Comment by adisbladis** [comment]
There is also [Niv](https://github.com/nmattia/niv), Flakes and other solutions to achieve this.
