### ISSUE TITLE
Rarely hitting the cache due to refering to deprecated nixpkgs-channels repo?

### ISSUE THREAD

**Issue by NobbZ** [nix-community/emacs-overlay#78]
Since a couple of weeks, my emacs related builds rarely hit the `nix-community` cache anymore, instead I ahve to build emacs locally.

Is this perhaps due to the deprecation of the `nixos/nixpkgs-channels` repository and the fact that it did not receive much updates anymore?

Some branches of the `-channels` repo seem to be roughly on par with the common repository, others are not. A branch for 20.09 does not exist on the channels repo.

**Comment by mjlbach** [comment]
This is a good point, one thing I did in the overlay I used to maintain is separately version nixpkgs used to build emacs in the overlay (https://github.com/mjlbach/emacs-pgtk-nativecomp-overlay). That way, if a user pins a specific version of the overlay, it still uses the appropriate nixpkgs version and hits the cache.

**Comment by jamesluke** [comment]
I noticed there are still a few references to "nixpkgs-channels". Do these lines need to be changed as well?:

https://github.com/nix-community/emacs-overlay/blob/f425f78d4062ea1006393e87d058cd2da2d441c5/hydra/spec.json#L21

https://github.com/nix-community/emacs-overlay/blob/f425f78d4062ea1006393e87d058cd2da2d441c5/hydra/default.nix#L29
