### ISSUE TITLE
Add CELPA to Emacs package lists

### ISSUE THREAD

**Issue by AndersonTorres** [nix-community/emacs-overlay#79]
Copied from https://github.com/NixOS/nixpkgs/issues/103047

**Project description**

_Celpa is the Conao's Elpa_

**Metadata**

* homepage URL: https://celpa.conao3.com/
* source URL: https://github.com/conao3/celpa
* license: gpl3+ 
* platforms: emacs :)

**Comment by adisbladis** [comment]
Closing for the same reason as the upstream nixpkgs issue was closed.
