### ISSUE TITLE
Packages installed with Quelpa

### ISSUE THREAD

**Issue by wiedzmin** [nix-community/emacs-overlay#8]
In addition to *lpa packages I have a tiny bunch of packages being installed using Quelpa. Those are the ones not yet pushed to *lpa archives or even not planned to, but useful. The situation itself mimics #6, in the sense of ignoring or specialized handlling of them. WDYT?

**Comment by adisbladis** [comment]
So just to be clear; This is mainly an issue with `emacsWithPackagesFromUsePackage`?
If so I think the fix is the same as for #6.

**Comment by talyz** [comment]
@wiedzmin Did #43 fix this for you?

**Comment by adisbladis** [comment]
I assume #43 fixes this, if not feel free to reopen.
