### ISSUE TITLE
How to debug an emacs crash?

### ISSUE THREAD

**Issue by little-dude** [nix-community/emacs-overlay#81]
Hi,

This is a question I [asked on the NixOS discourse](https://discourse.nixos.org/t/how-to-debug-emacs-crashes/10007), but maybe this is a better place.

Emacs crashes regularly when using lsp-mode with rust-analyzer. I’d like to debug this but it seems that I need a debug build of emacs for this: https://emacs.stackexchange.com/questions/14354/how-do-i-debug-an-emacs-crash

How can I install a debug build of emacs? I currently install emacs with home-manager: https://github.com/little-dude/dotfiles/blob/2a6750bbc769dd368e6ac06176764a15ea3ec462/programs/emacs/default.nix

Thanks!

**Comment by talyz** [comment]
Hi!

You should be able to build a debug build of, for example, the `emacsPgtk` package from this overlay with

```
nix-build -E 'with import <nixpkgs> { overlays = [ (import /path/to/emacs-overlay/default.nix) ]; }; enableDebugging emacsPgtk'
```

When the build is done, you can run `gdb` on the binary in `result/bin`.

I'll close this issue, since it's more of a discussion than an issue.
