### ISSUE TITLE
cachix cache

### ISSUE THREAD

**Issue by bbigras** [nix-community/emacs-overlay#9]
Someone on the forum said that it was planned.

Any progress on that?

**Comment by adisbladis** [comment]
I'm gonna close this since I think a binary cache would not be that beneficial (lots of spurious rebuilds, and not even cache.nixos.org builds emacs packages), and is better handled in https://github.com/nix-community/infra.

**Comment by adisbladis** [comment]
We have set this up for all builds happening on the nix-community build box now!
https://nix-community.org/#binary-cache
