### ISSUE TITLE
Emacs builds haven't updated in several days

### ISSUE THREAD

**Issue by leungbk** [nix-community/emacs-overlay#93]
Although there have been updates to upstream Emacs as well as its GitHub mirror within the last 48 hours, there have not been any corresponding updates for Emacs here in this overlay.

Melpa and Org updates have been proceeding as normal in the overlay during the same time frame.

**Comment by leungbk** [comment]
@adisbladis It looks like the Emacs builds on the emacs-overlay have not updated since late last week, even as the `emacs-mirror` repo has been updating normally and as the Org and Melpa builds on the overlay have continued working.

**Comment by spacekitteh** [comment]
Elpa hasn't updated in a month either.

**Comment by collares** [comment]
See #97 for the elpa issue.

**Comment by LEXUGE** [comment]
I think we should indeed merge the manual update before the automatic updater is available, else this breaks so much.

**Comment by spacekitteh** [comment]
Yes, please!

**Comment by collares** [comment]
I reopened the PR. But if I'm being honest, I think this time of year it's probably faster to go the automated route, simply because there are far more people with Nixpkgs commit privileges to ping about the emacs2nix update.

**Comment by LEXUGE** [comment]
Yes, I agree on that. However, the PR is not getting merged anytime soon (at least not within a few days), while people with `emacs-overlay` could be blocked to update their system for this reason. So we shall get it a quick fix and later when auto updater PR becomes merged, it should all be fine again.
