### ISSUE TITLE
elpa updates are not working

### ISSUE THREAD

**Issue by collares** [nix-community/emacs-overlay#97]
A new package "shell-command+" was added to ELPA on September 27th, and the plus sign broke emacs2nix. I think emacs2nix wants to print a warning message and skip the package, but the warning message uses unicode quotes and therefore we get the following cryptic message on CI:
```
+ eval '"/nix/store/40f2jldgkwp6ag4njd3x611gd59y370a-nixos-unstable.tar.gz/pkgs/applications/editors/emacs-modes/update-elpa"'
++ /nix/store/40f2jldgkwp6ag4njd3x611gd59y370a-nixos-unstable.tar.gz/pkgs/applications/editors/emacs-modes/update-elpa
invalid name: elpa2nix: <stdout>: commitBuffer: invalid argument (invalid character)
```
Adding shell-command+ is https://github.com/ttuegel/emacs2nix/pull/52 and removing unicode quotes is https://github.com/ttuegel/emacs2nix/pull/53; for the second thing we could set LANG="en_US.utf8" somewhere, but I don't think it's worth it for a pair of quotes.

This should be fixed once https://github.com/NixOS/nixpkgs/pull/107839 is merged.

**Comment by talyz** [comment]
NixOS/nixpkgs#107839 is now merged.
