### ISSUE TITLE
emacsGcc crash

### ISSUE THREAD

**Issue by panaak** [nix-community/emacs-overlay#98]
hi,

not sure if i'm reporting in the right place, but anyway..

i'm on the new Apple Silicon M1 architecture and  using emacs-overlay like this: `~/.config/nixpkgs/overlays/emacs.nix`

```
import (builtins.fetchTarball {
  url = https://github.com/nix-community/emacs-overlay/archive/master.tar.gz;
})

```

install whith:

`$ nix-env -iA nixpkgs.emacsGcc`

it compiles no problem. it runs and bytecompiles everything no problem, but after a while it crashes with:

`Assertion failed: (mach_vm_map(mach_task_self(), &address, size, 0, VM_FLAGS_ANYWHERE | VM_MAKE_TAG(VM_MEMORY_COREGRAPHICS_BACKINGSTORES), port, 0, false, prot, prot, VM_INHERIT_SHARE) == KERN_SUCCESS), function backing_map, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/SkyLight/SkyLight-569.6/SkyLight/Services/Windows/CGSBackingStore.c, line 192.
Fatal error 6: Aborted
[1]    2319 abort      emacs --fg-daemon`

any idea how to investigate?

**Comment by collares** [comment]
It seems very unlikely that this is a packaging issue, so I think your best bet is to report it with M-x report-emacs-bug. When you do, prepend "[feature/native-comp]" to the subject.

**Comment by panaak** [comment]
ok, will do. thanx for the hint..

**Comment by collares** [comment]
That being said, the error message points to a memory allocation failure. Are you seeing high memory usage from emacs?

**Comment by panaak** [comment]
not especially.. it's eating only about 300MB..

**Comment by panaak** [comment]
Seems it is fixed now. Installed a new nix package emacs-gcc-20201229.0 and looks stable now..

**Comment by mikucy** [comment]
Hi @collares , how did you fix this issue? My application has the same issue and it randomly happens.
