### ISSUE TITLE
emacsGit and emacsGcc doesn't compile on macos Big Sur

### ISSUE THREAD

**Issue by voidcontext** [nix-community/emacs-overlay#99]
The compilation fails with the following output:

```
...
configuring
configure flags: --prefix=/nix/store/k7gb6mbh3g56ms7i0v0p2h43x7721n3g-emacs-git-20201229.0 --disable-build-details --with-modules --with-ns --disable-ns-self-contained
checking for xcrun... no
checking for GNU Make... make
checking build system type... x86_64-apple-darwin20.2.0
checking host system type... x86_64-apple-darwin20.2.0
checking whether the C compiler works... no
configure: error: in `/private/tmp/nix-build-emacs-git-20201229.0.drv-0/source':
configure: error: C compiler cannot create executables
See `config.log' for more details
builder for '/nix/store/s3c2icfrms2apcnadv36399xfcxrv0d1-emacs-git-20201229.0.drv' failed with exit code 77
...
```

**Comment by purcell** [comment]
This works for me fwiw. I think the issue may be that your nixpkgs is not new enough to contain the bintools (?) tweaks that were necessary for Big Sur. I say this because of the message

> configure: error: C compiler cannot create executables

which I have seen caused by that issue.

**Comment by voidcontext** [comment]
Ok, this was a tricky one: I am using niv and nixpkgs pointed to the nix-channels repo, which has been archived and hasn't recieved any updates since Sept last year. Switching to the nixpkgs repo and updating it with niv solved the issue. 

Thanks @purcell for pointing me to the right direction!

**Comment by purcell** [comment]
Great, I've had to do that for a few local projects so far, agree that the niv defaults are currently not helping us Big Sur users.
